// This is an autogenerated file. Don't edit this file manually.
export interface appconfigpush {
  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''

  /**
   * The path to your app directory.
   */
  '--path <value>'?: string

  /**
   * The name of the app configuration.
   */
  '-c, --config <value>'?: string

  /**
   * Push configuration without asking for confirmation.
   */
  '-f, --force'?: ''
}
