// This is an autogenerated file. Don't edit this file manually.
export interface themepackage {
  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''

  /**
   * The path to your theme directory.
   */
  '--path <value>'?: string
}
