// This is an autogenerated file. Don't edit this file manually.
export interface themelanguageserver {
  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''

  /**
   * Use the dev preview version of theme check
Applies the typescript implementation of theme check to the theme
   */
  '--dev-preview'?: ''
}
