name: shopify-cli-extensions

type: go

up:
  - ruby:
      version: '3.1.1'
  - python:
      version: '3.9.10'
  - go:
      version: 1.17.6
      modules: true
  - node:
      version: v16.13.1
      yarn: v1.22.17
