version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directories:
      - "/"
      - "packages/*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "fs-extra"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      oclif:
        patterns:
          - "oclif"
          - "@oclif/*"
      nx:
        patterns:
          - "nx"
          - "@nx/*"
      esbuild:
        patterns:
          - "esbuild"
      babel:
        patterns:
          - "@babel/*"
      typescript:
        patterns:
          - "typescript"
      minor_versions:
        dependency-type: "production"
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - "ink"
          - "react"
      development_dependencies:
        dependency-type: "development"
        update-types:
          - 'minor'
          - 'patch'
