name: shopify-cli-next

up:
  - node:
      yarn: 1.22.18
      version: v18.0.0
      packages:
        - ./
  - ruby:
      version: 3.1.2
  - homebrew:
    - jq
    - delve

env:
  SHOPIFY_CONFIG: debug
  SHOPIFY_PARTNERS_API_ENV: production
  SHOPIFY_ADMIN_API_ENV: production
  SHOPIFY_STOREFRONT_RENDERER_API_ENV: production
  SHOPIFY_IDENTITY_API_ENV: production

open:
  app: http://localhost:3000

commands:
  graph:
    desc: 'Shows the graph of the project'
    run: yarn nx graph
  shopify:
    desc: 'Runs the Shopify CLI'
    run: yarn shopify
  create-app:
    desc: 'Runs the create-app CLI'
    run: yarn create-app
  create-hydrogen:
    desc: 'Runs the create-hydrogen CLI'
    run: yarn create-hydrogen
  clean:
    desc: 'Clean the packages'
    run: yarn run clean
  test:
    desc: 'Runs the tests'
    run: yarn run test:affected
  build:
    desc: 'Build the project'
    run: yarn run build:affected
  lint:
    desc: 'Lint the project'
    run: yarn run lint:affected
  lint:fix:
    desc: 'Fix the lint issues in the project'
    run: yarn run lint:fix:affected
  tsc:
    desc: 'Type-check the project'
    run: yarn run tsc:affected
  fixture:
    desc: 'Commands to interact with the fixture project'
    subcommands:
      shopify:
        desc: Runs Shopify with the fixture project
        run: yarn --cwd fixtures/app shopify
      build:
        desc: Build the fixture project
        run: yarn --cwd fixtures/app build
      dev:
        desc: Dev the fixture project
        run: yarn --cwd fixtures/app dev
      test:
        desc: Test the fixture project
        run: yarn --cwd fixtures/app test
      scaffold:
        desc: Scaffold in the fixture project
        run: yarn --cwd fixtures/app scaffold
  spin:
    desc: 'Run commands in spin context'
    run: bin/spin

