name: shopify-cli-next

up:
  - node:
      version: v22.2.0
      pnpm: 8.15.7
      package_manager: pnpm@8.15.7
      packages: []
  - packages:
    - jq
  - custom:
      name: 'Install PNPM dependencies'
      # we flip these two conditions to always run `pnpm install`
      # whenever we run dev up.
      met?: pnpm install
      meet: 'true'
  - custom:
      name: 'Get GraphQL schemas'
      # Always fetch these on dev up
      met?: pnpm graphql-codegen:get-graphql-schemas
      meet: 'true'

env:
  SHOPIFY_CLI_ENV: development
  SHOPIFY_SERVICE_ENV: production

open:
  app: http://localhost:3000

commands:
  graph:
    desc: 'Shows the graph of the project'
    run: pnpm nx graph
  shopify:
    desc: 'Runs the Shopify CLI'
    run: pnpm shopify
  create-app:
    desc: 'Runs the create-app CLI'
    run: pnpm create-app
  clean:
    desc: 'Clean the packages'
    run: pnpm run clean
  test:
    desc: 'Runs the tests'
    run: pnpm run test:affected
  build:
    desc: 'Build the project'
    run: pnpm run build:affected
  lint:
    desc: 'Lint the project'
    run: pnpm run lint:affected
  lint:fix:
    desc: 'Fix the lint issues in the project'
    run: pnpm run lint:fix:affected
  type-check:
    desc: 'Type-check the project'
    run: pnpm run type-check:affected
  spin:
    desc: 'Run commands in spin context'
    run: bin/spin
