packages:
  - packages/*
  - workspace
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - ngrok
  - nx
  - protobufjs
  - yarn
strictPeerDependencies: false
autoInstallPeers: true
linkWorkspacePackages: true
publicHoistPattern:
  - '*vitest*'
  - '*vite*'
  - '*eslint*'
  - '*prettier*'
