packages:
  - packages/*
  - workspace
autoInstallPeers: true
linkWorkspacePackages: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - nx
  - protobufjs
  - tree-sitter-typescript
  - yarn
publicHoistPattern:
  - '*vitest*'
  - '*vite*'
  - '*eslint*'
  - '*prettier*'
strictPeerDependencies: false
