// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app env pull',
  description: `Creates or updates an \`.env\` files that contains app and app extension environment variables.

  When an existing \`.env\` file is updated, changes to the variables are displayed in the terminal output. Existing variables and commented variables are preserved.`,
  overviewPreviewDescription: `Pull app and extensions environment variables.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app env pull',
          code: './examples/app-env-pull.example.sh',
          language: 'bash',
        },
      ],
      title: 'app env pull',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app env pull` command:',
    type: 'appenvpull',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data