// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app bulk execute',
  description: `Executes an Admin API GraphQL query or mutation on the specified store, as a bulk operation. Mutations are only allowed on dev stores.

  Bulk operations allow you to process large amounts of data asynchronously. Learn more about [bulk query operations](/docs/api/usage/bulk-operations/queries) and [bulk mutation operations](/docs/api/usage/bulk-operations/imports).

  Use [\`bulk status\`](/docs/api/shopify-cli/app/app-bulk-status) to check the status of your bulk operations.`,
  overviewPreviewDescription: `Execute bulk operations.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app bulk execute',
          code: './examples/app-bulk-execute.example.sh',
          language: 'bash',
        },
      ],
      title: 'app bulk execute',
    },
  },
  definitions: [
    {
      title: 'Flags',
      description: 'The following flags are available for the `app bulk execute` command:',
      type: 'appbulkexecute',
    },
  ],
  category: 'app',
  related: [],
}

export default data
