// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app info',
  description: `The following flags are available for the \`app info\` command:`,
  overviewPreviewDescription: `Print basic information about your app and extensions.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app info',
          code: './examples/app-info.example.sh',
          language: 'bash',
        },
      ],
      title: 'app info',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app info` command:',
    type: 'appinfo',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data