// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app release',
  description: `Releases an existing app version. Pass the name of the version that you want to release using the \`--version\` flag.`,
  overviewPreviewDescription: `Release an app version.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app release',
          code: './examples/app-release.example.sh',
          language: 'bash',
        },
      ],
      title: 'app release',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app release` command:',
    type: 'apprelease',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data