// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app dev',
  description: `The following flags are available for the \`app dev\` command:`,
  overviewPreviewDescription: `Run the app.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app dev',
          code: './examples/app-dev.example.sh',
          language: 'bash',
        },
      ],
      title: 'app dev',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app dev` command:',
    type: 'appdev',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data