// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app import-dashboard-extensions',
  description: `Import dashboard-managed extensions into your app.`,
  overviewPreviewDescription: `Import dashboard-managed extensions into your app.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app import-dashboard-extensions',
          code: './examples/app-import-dashboard-extensions.example.sh',
          language: 'bash',
        },
      ],
      title: 'app import-dashboard-extensions',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app import-dashboard-extensions` command:',
    type: 'appimportdashboardextensions',
  },
  ],
  category: 'Commands',
  subCategory: 'app',
  related: [
  ],
}

export default data