// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app build',
  description: `The following flags are available for the \`app build\` command:`,
  overviewPreviewDescription: `Build the app, including extensions.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app build',
          code: './examples/app-build.example.sh',
          language: 'bash',
        },
      ],
      title: 'app build',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app build` command:',
    type: 'appbuild',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data