// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app import-custom-data-definitions',
  description: `Import metafield and metaobject definitions from your development store. [Read more about declarative custom data definitions](/docs/apps/build/custom-data/declarative-custom-data-definitions).`,
  overviewPreviewDescription: `Import metafield and metaobject definitions.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app import-custom-data-definitions',
          code: './examples/app-import-custom-data-definitions.example.sh',
          language: 'bash',
        },
      ],
      title: 'app import-custom-data-definitions',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app import-custom-data-definitions` command:',
    type: 'appimportcustomdatadefinitions',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data