// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app config use',
  description: `Sets default configuration when you run app-related CLI commands. If you omit the \`config-name\` parameter, then you'll be prompted to choose from the configuration files in your project.`,
  overviewPreviewDescription: `Activate an app configuration.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app config use',
          code: './examples/app-config-use.example.sh',
          language: 'bash',
        },
      ],
      title: 'app config use',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app config use` command:',
    type: 'appconfiguse',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data