// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app function replay',
  description: `The following flags are available for the \`app function replay\` command:`,
  overviewPreviewDescription: `Replays a function run from an app log.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app function replay',
          code: './examples/app-function-replay.example.sh',
          language: 'bash',
        },
      ],
      title: 'app function replay',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app function replay` command:',
    type: 'appfunctionreplay',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data