// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app import-payments-dashboard-extensions',
  description: `Import dashboard-managed payments extensions into your app.`,
  overviewPreviewDescription: `Import dashboard-managed payments extensions into your app.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app import-payments-dashboard-extensions',
          code: './examples/app-import-payments-dashboard-extensions.example.sh',
          language: 'bash',
        },
      ],
      title: 'app import-payments-dashboard-extensions',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app import-payments-dashboard-extensions` command:',
    type: 'appimportpaymentsdashboardextensions',
  },
  ],
  category: 'Commands',
  subCategory: 'app',
  related: [
  ],
}

export default data