// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app bulk execute',
  description: `The following flags are available for the \`app bulk execute\` command:`,
  overviewPreviewDescription: `Execute bulk operations.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app bulk execute',
          code: './examples/app-bulk-execute.example.sh',
          language: 'bash',
        },
      ],
      title: 'app bulk execute',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app bulk execute` command:',
    type: 'appbulkexecute',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data