// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app deploy',
  description: `[Builds the app](https://shopify.dev/docs/apps/tools/cli/commands#build), then deploys your app configuration and extensions.

  This command creates an app version, which is a snapshot of your app configuration and all extensions, including the app extensions that you manage in the Partner Dashboard. This version is then released to users.

  This command doesn't deploy your [web app](https://shopify.dev/docs/apps/tools/cli/structure#web-components). You need to [deploy your web app](https://shopify.dev/docs/apps/deployment/web) to your own hosting solution.
  `,
  overviewPreviewDescription: `Deploy your Shopify app.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app deploy',
          code: './examples/app-deploy.example.sh',
          language: 'bash',
        },
      ],
      title: 'app deploy',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app deploy` command:',
    type: 'appdeploy',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data