// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app import-flow-legacy-extensions',
  description: `Import dashboard-managed flow extensions into your app.`,
  overviewPreviewDescription: `Import dashboard-managed flow extensions into your app.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app import-flow-legacy-extensions',
          code: './examples/app-import-flow-legacy-extensions.example.sh',
          language: 'bash',
        },
      ],
      title: 'app import-flow-legacy-extensions',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app import-flow-legacy-extensions` command:',
    type: 'appimportflowlegacyextensions',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data