// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app build',
  description: `This command executes the build script specified in the element's TOML file. You can specify a custom script in the file. To learn about configuration files in Shopify apps, refer to [App configuration](https://shopify.dev/docs/apps/tools/cli/configuration).

  If you're building a [theme app extension](https://shopify.dev/docs/apps/online-store/theme-app-extensions), then running the \`build\` command runs [Theme Check](https://shopify.dev/docs/themes/tools/theme-check) against your extension to ensure that it's valid.`,
  overviewPreviewDescription: `Build the app, including extensions.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app build',
          code: './examples/app-build.example.sh',
          language: 'bash',
        },
      ],
      title: 'app build',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app build` command:',
    type: 'appbuild',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data