// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app execute',
  description: `Executes a GraphQL query or mutation on the specified store, and writes the result to STDOUT or a file.`,
  overviewPreviewDescription: `Execute GraphQL queries and mutations.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app execute',
          code: './examples/app-execute.example.sh',
          language: 'bash',
        },
      ],
      title: 'app execute',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app execute` command:',
    type: 'appexecute',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data