// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app dev clean',
  description: `Stop the app preview that was started with \`shopify app dev\`.

  It restores the app's active version to the selected development store.
  `,
  overviewPreviewDescription: `Cleans up the app preview from the selected store.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app dev clean',
          code: './examples/app-dev-clean.example.sh',
          language: 'bash',
        },
      ],
      title: 'app dev clean',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app dev clean` command:',
    type: 'appdevclean',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data