// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app dev',
  description: `Builds and previews your app on a dev store, and watches for changes. [Read more about testing apps locally](/docs/apps/build/cli-for-apps/test-apps-locally).`,
  overviewPreviewDescription: `Run the app.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app dev',
          code: './examples/app-dev.example.sh',
          language: 'bash',
        },
      ],
      title: 'app dev',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app dev` command:',
    type: 'appdev',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data