// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app config link',
  description: `Pulls app configuration from the Partner Dashboard and creates or overwrites a configuration file. You can create a new app with this command to start with a default configuration file.

  For more information on the format of the created TOML configuration file, refer to the [App configuration](https://shopify.dev/docs/apps/tools/cli/configuration) page.
  `,
  overviewPreviewDescription: `Fetch your app configuration from the Partner Dashboard.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app config link',
          code: './examples/app-config-link.example.sh',
          language: 'bash',
        },
      ],
      title: 'app config link',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app config link` command:',
    type: 'appconfiglink',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data