// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app function fixture-override',
  description: `Create a new fixture by overriding values from an existing one`,
  overviewPreviewDescription: `Create a new fixture by overriding values from an existing one`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app function fixture-override',
          code: './examples/app-function-fixture-override.example.sh',
          language: 'bash',
        },
      ],
      title: 'app function fixture-override',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app function fixture-override` command:',
    type: 'appfunctionfixtureoverride',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data