// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app config validate',
  description: `The following flags are available for the \`app config validate\` command:`,
  overviewPreviewDescription: `Validate your app configuration and extensions.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app config validate',
          code: './examples/app-config-validate.example.sh',
          language: 'bash',
        },
      ],
      title: 'app config validate',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app config validate` command:',
    type: 'appconfigvalidate',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data