// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app config pull',
  description: `The following flags are available for the \`app config pull\` command:`,
  overviewPreviewDescription: `Refresh an already-linked app configuration without prompts.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app config pull',
          code: './examples/app-config-pull.example.sh',
          language: 'bash',
        },
      ],
      title: 'app config pull',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app config pull` command:',
    type: 'appconfigpull',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data