// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app bulk cancel',
  description: `Cancels a running bulk operation by ID.`,
  overviewPreviewDescription: `Cancel a bulk operation.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app bulk cancel',
          code: './examples/app-bulk-cancel.example.sh',
          language: 'bash',
        },
      ],
      title: 'app bulk cancel',
    },
  },
  definitions: [
    {
      title: 'Flags',
      description: 'The following flags are available for the `app bulk cancel` command:',
      type: 'appbulkcancel',
    },
  ],
  category: 'app',
  related: [],
}

export default data
