// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app execute',
  description: `Executes an Admin API GraphQL query or mutation on the specified store. Mutations are only allowed on dev stores.

  For operations that process large amounts of data, use [\`bulk execute\`](/docs/api/shopify-cli/app/app-bulk-execute) instead.`,
  overviewPreviewDescription: `Execute GraphQL queries and mutations.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app execute',
          code: './examples/app-execute.example.sh',
          language: 'bash',
        },
      ],
      title: 'app execute',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app execute` command:',
    type: 'appexecute',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data