// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app function test',
  description: `Builds the function to WebAssembly and then automatically runs tests if a \`tests\` folder exists. This is useful for ensuring your function works correctly before deployment.

If a test command is specified in your \`shopify.extension.toml\` file under \`[extensions.test]\`, that command will be used instead of the default vitest runner:

\`\`\`toml
[[extensions]]
name = "my-function"
handle = "my-function"
type = "function"

  [extensions.test]
  command = "npx vitest run"
\`\`\`

If no custom test command is found, the command will automatically discover and run \`.test.ts\` and \`.test.js\` files using vitest.`,
  overviewPreviewDescription: `Builds the function and runs all tests in the test folder.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app function test',
          code: './examples/app-function-test.example.sh',
          language: 'bash',
        },
      ],
      title: 'app function test',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app function test` command:',
    type: 'appfunctiontest',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data