// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app init',
  description: `Create a new app project`,
  overviewPreviewDescription: `Create a new app project`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app init',
          code: './examples/app-init.example.sh',
          language: 'bash',
        },
      ],
      title: 'app init',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app init` command:',
    type: 'appinit',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data