// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app function typegen',
  description: `The following flags are available for the \`app function typegen\` command:`,
  overviewPreviewDescription: `Generate GraphQL types for a function.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app function typegen',
          code: './examples/app-function-typegen.example.sh',
          language: 'bash',
        },
      ],
      title: 'app function typegen',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app function typegen` command:',
    type: 'appfunctiontypegen',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data