// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app function info',
  description: `The information returned includes the following:

  - The function handle
  - The function name
  - The function API version
  - The function runner path
  - The schema path
  - The WASM path
  - The targeting configuration`,
  overviewPreviewDescription: `Print basic information about your function.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app function info',
          code: './examples/app-function-info.example.sh',
          language: 'bash',
        },
      ],
      title: 'app function info',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app function info` command:',
    type: 'appfunctioninfo',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data