// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app bulk status',
  description: `The following flags are available for the \`app bulk status\` command:`,
  overviewPreviewDescription: `Check the status of bulk operations.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app bulk status',
          code: './examples/app-bulk-status.example.sh',
          language: 'bash',
        },
      ],
      title: 'app bulk status',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app bulk status` command:',
    type: 'appbulkstatus',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data