// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app function testgen',
  description: `Prompts users to select a function run log and generates test fixtures from it. These test cases based on real function executions act as an E2E test suite for the function.`,
  overviewPreviewDescription: `Generates test files from a function run log.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app function testgen',
          code: './examples/app-function-testgen.example.sh',
          language: 'bash',
        },
      ],
      title: 'app function testgen',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `app function testgen` command:',
    type: 'appfunctiontestgen',
  },
  ],
  category: 'app',
  related: [
  ],
}

export default data