// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'commands',
  description: `list all the commands`,
  overviewPreviewDescription: `list all the commands`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'commands',
          code: './examples/commands.example.sh',
          language: 'bash',
        },
      ],
      title: 'commands',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `commands` command:',
    type: 'commands',
  },
  ],
  category: 'Universal commands',
  related: [
  ],
}

export default data