// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'config autocorrect off',
  description: `Disable autocorrect. Off by default.

  When autocorrection is enabled, Shopify CLI automatically runs a corrected version of your command if a correction is available.

  When autocorrection is disabled, you need to confirm that you want to run corrections for mistyped commands.
`,
  overviewPreviewDescription: `Disable autocorrect. Off by default.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'config autocorrect off',
          code: './examples/config-autocorrect-off.example.sh',
          language: 'bash',
        },
      ],
      title: 'config autocorrect off',
    },
  },
  definitions: [
  ],
  category: 'Universal commands',
  related: [
  ],
}

export default data