// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'config autoupgrade on',
  description: `Enable automatic upgrades for Shopify CLI.

  When auto-upgrade is enabled, Shopify CLI automatically updates to the latest version once per day. Major version upgrades are skipped and must be done manually.

  To disable auto-upgrade, run \`shopify config autoupgrade off\`.
`,
  overviewPreviewDescription: `Enable automatic upgrades for Shopify CLI.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'config autoupgrade on',
          code: './examples/config-autoupgrade-on.example.sh',
          language: 'bash',
        },
      ],
      title: 'config autoupgrade on',
    },
  },
  definitions: [
  ],
  category: 'general commands',
  related: [
  ],
}

export default data