// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'config autoupgrade off',
  description: `Disable automatic upgrades for Shopify CLI.

  When auto-upgrade is disabled, Shopify CLI won't automatically update. Run \`shopify upgrade\` to update manually.

  To enable auto-upgrade, run \`shopify config autoupgrade on\`.
`,
  overviewPreviewDescription: `Disable automatic upgrades for Shopify CLI.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'config autoupgrade off',
          code: './examples/config-autoupgrade-off.example.sh',
          language: 'bash',
        },
      ],
      title: 'config autoupgrade off',
    },
  },
  definitions: [
  ],
  category: 'general commands',
  related: [
  ],
}

export default data