// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen deploy',
  description: `Builds and deploys a Hydrogen storefront to Oxygen.`,
  overviewPreviewDescription: `Builds and deploys a Hydrogen storefront to Oxygen.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen deploy',
          code: './examples/hydrogen-deploy.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen deploy',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen deploy` command:',
    type: 'hydrogendeploy',
  },
  ],
  category: 'hydrogen commands',
  related: [
  ],
}

export default data