// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen env list',
  description: `Lists all environments available on the linked Hydrogen storefront.`,
  overviewPreviewDescription: `Lists all environments available on the linked Hydrogen storefront.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen env list',
          code: './examples/hydrogen-env-list.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen env list',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen env list` command:',
    type: 'hydrogenenvlist',
  },
  ],
  category: 'hydrogen',
  related: [
  ],
}

export default data