// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen preview',
  description: `Runs a Hydrogen storefront in an Oxygen worker for production.`,
  overviewPreviewDescription: `Runs a Hydrogen storefront in an Oxygen worker for production.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen preview',
          code: './examples/hydrogen-preview.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen preview',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen preview` command:',
    type: 'hydrogenpreview',
  },
  ],
  category: 'hydrogen commands',
  related: [
  ],
}

export default data