// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen dev',
  description: `Runs Hydrogen storefront in an Oxygen worker for development.`,
  overviewPreviewDescription: `Runs Hydrogen storefront in an Oxygen worker for development.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen dev',
          code: './examples/hydrogen-dev.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen dev',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen dev` command:',
    type: 'hydrogendev',
  },
  ],
  category: 'hydrogen commands',
  related: [
  ],
}

export default data