// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen login',
  description: `Login to your Shopify account.`,
  overviewPreviewDescription: `Login to your Shopify account.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen login',
          code: './examples/hydrogen-login.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen login',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen login` command:',
    type: 'hydrogenlogin',
  },
  ],
  category: 'hydrogen commands',
  related: [
  ],
}

export default data