// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen check',
  description: `Returns diagnostic information about a Hydrogen storefront.`,
  overviewPreviewDescription: `Returns diagnostic information about a Hydrogen storefront.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen check',
          code: './examples/hydrogen-check.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen check',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen check` command:',
    type: 'hydrogencheck',
  },
  ],
  category: 'hydrogen commands',
  related: [
  ],
}

export default data