// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen setup markets',
  description: `Adds support for multiple [markets](https://shopify.dev/docs/custom-storefronts/hydrogen/markets) to your project by using the URL structure.`,
  overviewPreviewDescription: `Adds support for multiple [markets](https://shopify.dev/docs/custom-storefronts/hydrogen/markets) to your project by using the URL structure.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen setup markets',
          code: './examples/hydrogen-setup-markets.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen setup markets',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen setup markets` command:',
    type: 'hydrogensetupmarkets',
  },
  ],
  category: 'hydrogen',
  related: [
  ],
}

export default data