// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen env pull',
  description: `The following flags are available for the \`hydrogen env pull\` command:`,
  overviewPreviewDescription: `The following flags are available for the \`hydrogen env pull\` command:`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen env pull',
          code: './examples/hydrogen-env-pull.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen env pull',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen env pull` command:',
    type: 'hydrogenenvpull',
  },
  ],
  category: 'hydrogen',
  related: [
  ],
}

export default data