// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen setup css',
  description: `Adds support for certain CSS strategies to your project.`,
  overviewPreviewDescription: `Adds support for certain CSS strategies to your project.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen setup css',
          code: './examples/hydrogen-setup-css.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen setup css',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen setup css` command:',
    type: 'hydrogensetupcss',
  },
  ],
  category: 'hydrogen',
  related: [
  ],
}

export default data