// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen list',
  description: `Returns a list of Hydrogen storefronts available on a given shop.`,
  overviewPreviewDescription: `Returns a list of Hydrogen storefronts available on a given shop.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen list',
          code: './examples/hydrogen-list.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen list',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen list` command:',
    type: 'hydrogenlist',
  },
  ],
  category: 'hydrogen commands',
  related: [
  ],
}

export default data