// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen setup',
  description: `Scaffold routes and core functionality.`,
  overviewPreviewDescription: `Scaffold routes and core functionality.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen setup',
          code: './examples/hydrogen-setup.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen setup',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen setup` command:',
    type: 'hydrogensetup',
  },
  ],
  category: 'hydrogen',
  related: [
  ],
}

export default data