// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen upgrade',
  description: `Upgrade Hydrogen project dependencies, preview features, fixes and breaking changes. The command also generates an instruction file for each upgrade.`,
  overviewPreviewDescription: `Upgrade Hydrogen project dependencies, preview features, fixes and breaking changes. The command also generates an instruction file for each upgrade.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen upgrade',
          code: './examples/hydrogen-upgrade.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen upgrade',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen upgrade` command:',
    type: 'hydrogenupgrade',
  },
  ],
  category: 'hydrogen',
  related: [
  ],
}

export default data