// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen generate route',
  description: `Generates a standard Shopify route.`,
  overviewPreviewDescription: `Generates a standard Shopify route.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen generate route',
          code: './examples/hydrogen-generate-route.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen generate route',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen generate route` command:',
    type: 'hydrogengenerateroute',
  },
  ],
  category: 'hydrogen commands',
  related: [
  ],
}

export default data