// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen logout',
  description: `Logout of your local session.`,
  overviewPreviewDescription: `Logout of your local session.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen logout',
          code: './examples/hydrogen-logout.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen logout',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen logout` command:',
    type: 'hydrogenlogout',
  },
  ],
  category: 'hydrogen commands',
  related: [
  ],
}

export default data