// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'hydrogen codegen',
  description: `Automatically generates GraphQL types for your project’s Storefront API queries.`,
  overviewPreviewDescription: `Automatically generates GraphQL types for your project’s Storefront API queries.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'hydrogen codegen',
          code: './examples/hydrogen-codegen.example.sh',
          language: 'bash',
        },
      ],
      title: 'hydrogen codegen',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `hydrogen codegen` command:',
    type: 'hydrogencodegen',
  },
  ],
  category: 'hydrogen',
  related: [
  ],
}

export default data