// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'organization list',
  description: `The following flags are available for the \`organization list\` command:`,
  overviewPreviewDescription: `List Shopify organizations you have access to.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'organization list',
          code: './examples/organization-list.example.sh',
          language: 'bash',
        },
      ],
      title: 'organization list',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `organization list` command:',
    type: 'organizationlist',
  },
  ],
  category: 'general commands',
  related: [
  ],
}

export default data