// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'search',
  description: `Starts a search on shopify.dev.`,
  overviewPreviewDescription: `Starts a search on shopify.dev.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'search',
          code: './examples/search.example.sh',
          language: 'bash',
        },
      ],
      title: 'search',
    },
  },
  definitions: [
  ],
  category: 'Universal commands',
  related: [
  ],
}

export default data