// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'store create',
  description: `Creates a new Shopify store associated with your account.

By default, creates a trial store. Use \`--dev\` to create a development store instead.`,
  overviewPreviewDescription: `Create a new Shopify store.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'store create',
          code: './examples/store-create.example.sh',
          language: 'bash',
        },
      ],
      title: 'store create',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `store create` command:',
    type: 'storecreate',
  },
  ],
  category: 'store',
  related: [
  ],
}

export default data