// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'store auth logout',
  description: `Clears the locally stored store auth for the specified store on this machine.

This does not revoke the app or remove granted scopes on Shopify.`,
  overviewPreviewDescription: `Clear locally stored store auth for a store.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'store auth logout',
          code: './examples/store-auth-logout.example.sh',
          language: 'bash',
        },
      ],
      title: 'store auth logout',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `store auth logout` command:',
    type: 'storeauthlogout',
  },
  ],
  category: 'store',
  related: [
  ],
}

export default data