// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'store auth',
  description: `Authenticates the app against the specified store for store commands and stores an online access token for later reuse.

Re-run this command if the stored token is missing, expires, or no longer has the scopes you need.

To inspect the locally stored auth state for a store, run [\`shopify store auth info\`](/docs/api/shopify-cli/store/store-auth-info).

To clear the locally stored auth state for a store, run [\`shopify store auth logout\`](/docs/api/shopify-cli/store/store-auth-logout).`,
  overviewPreviewDescription: `Authenticate an app against a store for store commands.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'store auth',
          code: './examples/store-auth.example.sh',
          language: 'bash',
        },
      ],
      title: 'store auth',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `store auth` command:',
    type: 'storeauth',
  },
  ],
  category: 'store',
  related: [
  ],
}

export default data