// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme open',
  description: `Returns links that let you preview the specified theme. The following links are returned:

  - A link to the [editor](/docs/themes/tools/online-editor) for the theme in the Shopify admin.
  - A [preview link](https://help.shopify.com/manual/online-store/themes/adding-themes#share-a-theme-preview-with-others) that you can share with other developers.

  If you don't specify a theme, then you're prompted to select the theme to open from the list of the themes in your store.`,
  overviewPreviewDescription: `Opens the preview of your remote theme.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme open',
          code: './examples/theme-open.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme open',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme open` command:',
    type: 'themeopen',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data