// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme profile',
  description: `Profile the Shopify Liquid on a given page.

  This command will open a web page with the Speedscope profiler detailing the time spent executing Liquid on the given page.`,
  overviewPreviewDescription: `Profile the Liquid rendering of a theme page.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme profile',
          code: './examples/theme-profile.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme profile',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme profile` command:',
    type: 'themeprofile',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data