// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme generate block',
  description: `Creates a new [theme block](/docs/themes/architecture/blocks) in your local theme directory.

  The block is created in the \`blocks\` directory with the basic structure needed, including schema and settings.

  You can specify the type of block to generate using the \`--type\` flag. The block will be created with appropriate default settings based on the type.`,
  overviewPreviewDescription: `Creates and adds a new block file to your local theme directory`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme generate block',
          code: './examples/theme-generate-block.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme generate block',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme generate block` command:',
    type: 'themegenerateblock',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data