// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme metafields pull',
  description: `Retrieves metafields from Shopify Admin.

If the metafields file already exists, it will be overwritten.`,
  overviewPreviewDescription: `Download metafields definitions from your shop into a local file.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme metafields pull',
          code: './examples/theme-metafields-pull.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme metafields pull',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme metafields pull` command:',
    type: 'thememetafieldspull',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data