// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme preview',
  description: `The following flags are available for the \`theme preview\` command:`,
  overviewPreviewDescription: `Applies JSON overrides to a theme and returns a preview URL.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme preview',
          code: './examples/theme-preview.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme preview',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme preview` command:',
    type: 'themepreview',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data