// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme generate section',
  description: `Creates a new [theme section](/docs/themes/architecture/sections) in your local theme directory.

  The section is created in the \`sections\` directory with the basic structure needed, including schema, settings, and blocks.

  You can specify the type of section to generate using the \`--type\` flag. The section will be created with appropriate default settings and blocks based on the type.`,
  overviewPreviewDescription: `Creates and adds a new section file to your local theme directory`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme generate section',
          code: './examples/theme-generate-section.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme generate section',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme generate section` command:',
    type: 'themegeneratesection',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data