// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme pull',
  description: `Retrieves theme files from Shopify.

If no theme is specified, then you're prompted to select the theme to pull from the list of the themes in your store.`,
  overviewPreviewDescription: `Download your remote theme files locally.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme pull',
          code: './examples/theme-pull.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme pull',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme pull` command:',
    type: 'themepull',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data