// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme duplicate',
  description: `The following flags are available for the \`theme duplicate\` command:`,
  overviewPreviewDescription: `Duplicates a theme from your theme library.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme duplicate',
          code: './examples/theme-duplicate.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme duplicate',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme duplicate` command:',
    type: 'themeduplicate',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data