// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme delete',
  description: `The following flags are available for the \`theme delete\` command:`,
  overviewPreviewDescription: `Delete remote themes from the connected store. This command can't be undone.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme delete',
          code: './examples/theme-delete.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme delete',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme delete` command:',
    type: 'themedelete',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data