// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme console',
  description: `Starts the Shopify Liquid REPL (read-eval-print loop) tool. This tool provides an interactive terminal interface for evaluating Liquid code and exploring Liquid objects, filters, and tags using real store data.

  You can also provide context to the console using a URL, as some Liquid objects are context-specific`,
  overviewPreviewDescription: `Shopify Liquid REPL (read-eval-print loop) tool`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme console',
          code: './examples/theme-console.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme console',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme console` command:',
    type: 'themeconsole',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data