// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme rename',
  description: `The following flags are available for the \`theme rename\` command:`,
  overviewPreviewDescription: `Renames an existing theme.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme rename',
          code: './examples/theme-rename.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme rename',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme rename` command:',
    type: 'themerename',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data