// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme open',
  description: `The following flags are available for the \`theme open\` command:`,
  overviewPreviewDescription: `Opens the preview of your remote theme.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme open',
          code: './examples/theme-open.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme open',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme open` command:',
    type: 'themeopen',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data