// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'theme package',
  description: `The following flags are available for the \`theme package\` command:`,
  overviewPreviewDescription: `Package your theme into a .zip file, ready to upload to the Online Store.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'theme package',
          code: './examples/theme-package.example.sh',
          language: 'bash',
        },
      ],
      title: 'theme package',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `theme package` command:',
    type: 'themepackage',
  },
  ],
  category: 'theme',
  related: [
  ],
}

export default data