// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'upgrade',
  description: `Shows details on how to upgrade Shopify CLI.`,
  overviewPreviewDescription: `Shows details on how to upgrade Shopify CLI.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'upgrade',
          code: './examples/upgrade.example.sh',
          language: 'bash',
        },
      ],
      title: 'upgrade',
    },
  },
  definitions: [
  ],
  category: 'general commands',
  related: [
  ],
}

export default data