// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'upgrade',
  description: `If the CLI is installed as a dependency of your app project, this command will upgrade it. Otherwise, refer to the [upgrade](https://shopify.dev/docs/api/shopify-cli#upgrade) documentation.`,
  overviewPreviewDescription: `Upgrade your CLI dependency.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'upgrade',
          code: './examples/upgrade.example.sh',
          language: 'bash',
        },
      ],
      title: 'upgrade',
    },
  },
  definitions: [
  {
    title: 'Flags',
    description: 'The following flags are available for the `upgrade` command:',
    type: 'upgrade',
  },
  ],
  category: 'Universal commands',
  related: [
  ],
}

export default data