name = "Checkout Post Purchase"
type = "checkout_post_purchase"

uid = "example"
description = "example"
api_version = "example"
extension_points = "example"
[capabilities]
network_access = true
block_progress = true
api_access = true
[capabilities.collect_buyer_consent]
sms_marketing = true
customer_privacy = true

[capabilities.iframe]
sources = ["example"]


[supported_features]
runs_offline = true

[settings]
[[settings.fields]]
key = "example"
name = "example"
description = "example"
required = true
default_value = "example"
type = "example"
validations = "example"
marketingActivityCreateUrl = "example"
marketingActivityDeleteUrl = "example"


[[metafields]]
namespace = "example"
key = "example"
