/**
 * Generates `src/data-embedded/`, mirroring the `.json.gz` schemas in
 * `src/data/`. For every `<api>_<version>.json.gz` it writes a
 * `<api>_<version>.ts` module that embeds those gzipped bytes as a base64
 * constant and exports a ready {@link SchemaSource}. It also writes a per-API
 * module (`<api>.ts`, every version of that API) and an `index.ts` aggregate
 * (every embedded API/version), so a consumer can import at whichever
 * granularity it needs (see src/schema-embedded.ts). Every API/version with a
 * schema file is embedded.
 *
 * Regeneration is skipped when `src/data-embedded` is already newer than every
 * input (the `.json.gz` schemas, the catalog, and this script), so the script
 * is a cheap no-op to depend on from `build`, `build:watch`, `typecheck`, and
 * the embedded-source test. Set `EMBED_FORCE` to regenerate unconditionally.
 */
import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  readdirSync,
  statSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(here, "../src/data");
const outDir = path.resolve(here, "../src/data-embedded");

interface CatalogVersion {
  name: string;
  latestVersion?: boolean;
  releaseCandidate?: boolean;
}

const catalog = JSON.parse(
  readFileSync(path.join(dataDir, "supported-versions-schema.json"), "utf-8"),
) as Record<string, CatalogVersion[]>;

const embeddedIsUpToDate = (): boolean => {
  const indexFile = path.join(outDir, "index.ts");
  if (!existsSync(indexFile)) {
    return false;
  }
  const inputs = [
    fileURLToPath(import.meta.url),
    path.join(dataDir, "supported-versions-schema.json"),
    ...readdirSync(dataDir)
      .filter((f) => f.endsWith(".json.gz"))
      .map((f) => path.join(dataDir, f)),
  ];
  const newestInput = Math.max(...inputs.map((p) => statSync(p).mtimeMs));
  return statSync(indexFile).mtimeMs >= newestInput;
};

if (!process.env.EMBED_FORCE && embeddedIsUpToDate()) {
  console.log("embed-schemas: src/data-embedded is up to date; skipping");
  process.exit(0);
}

// `<api>_<version>` where version is `YYYY-MM` or `unstable`; api may itself
// contain underscores (e.g. `functions_cart_transform`).
const FILE_RE = /^(.*)_(\d{4}-\d{2}|unstable)\.json\.gz$/;

const byApi = new Map<string, CatalogVersion[]>();
for (const file of readdirSync(dataDir).sort()) {
  const match = file.match(FILE_RE);
  if (!match) {
    continue;
  }
  const [, api, version] = match;
  const flags = catalog[api]?.find((v) => v.name === version);
  const entry: CatalogVersion = {
    name: version,
    latestVersion: flags?.latestVersion === true,
    ...(flags?.releaseCandidate ? { releaseCandidate: true } : {}),
  };
  if (!byApi.has(api)) {
    byApi.set(api, []);
  }
  byApi.get(api)!.push(entry);
}

const header =
  "// AUTO-GENERATED by scripts/embed-schemas.ts — do not edit.\n// Regenerate with `pnpm embed-schemas`.\n";
const safeIdent = (s: string): string => s.replace(/[^A-Za-z0-9]/g, "_");

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const embeddedApis = [...byApi.keys()].sort();
let moduleCount = 0;

for (const api of embeddedApis) {
  const versions = byApi.get(api)!;

  // One module per version.
  for (const version of versions) {
    const gz = readFileSync(
      path.join(dataDir, `${api}_${version.name}.json.gz`),
    );
    const base64 = gz.toString("base64");
    const body = `${header}import { createEmbeddedSchemaSource } from "../schemaOperations/embeddedSchemaSource.js";

const CATALOG = ${JSON.stringify({ [api]: [version] }, null, 2)};

const SCHEMAS: Record<string, string> = ${JSON.stringify(
      { [`${api}:${version.name}`]: base64 },
      null,
      2,
    )};

export default createEmbeddedSchemaSource(CATALOG, SCHEMAS);
`;
    writeFileSync(path.join(outDir, `${api}_${version.name}.ts`), body);
    moduleCount++;
  }

  // Per-API module: every version of this API.
  const versionImports = versions
    .map(
      (v) => `import ${safeIdent(`v_${v.name}`)} from "./${api}_${v.name}.js";`,
    )
    .join("\n");
  const versionList = versions
    .map((v) => `  ${safeIdent(`v_${v.name}`)},`)
    .join("\n");
  writeFileSync(
    path.join(outDir, `${api}.ts`),
    `${header}import { mergeSchemaSources } from "../schemaOperations/embeddedSchemaSource.js";
${versionImports}

export default mergeSchemaSources([
${versionList}
]);
`,
  );

  const sizeKiB =
    versions.reduce(
      (n, v) =>
        n + readFileSync(path.join(dataDir, `${api}_${v.name}.json.gz`)).length,
      0,
    ) / 1024;
  console.log(
    `embedded ${api} [${versions.map((v) => v.name).join(", ")}] (${sizeKiB.toFixed(0)} KiB gz)`,
  );
}

// All-API aggregate.
const apiImports = embeddedApis
  .map((a) => `import ${safeIdent(`api_${a}`)} from "./${a}.js";`)
  .join("\n");
const apiList = embeddedApis
  .map((a) => `  ${safeIdent(`api_${a}`)},`)
  .join("\n");
writeFileSync(
  path.join(outDir, "index.ts"),
  `${header}import { mergeSchemaSources } from "../schemaOperations/embeddedSchemaSource.js";
${apiImports}

export const EMBEDDED_APIS = ${JSON.stringify(embeddedApis)} as const;

export const embeddedSchemaSource = mergeSchemaSources([
${apiList}
]);
`,
);

console.log(
  `wrote ${moduleCount} version module(s) + ${embeddedApis.length} API module(s) + index to ${outDir}`,
);
