import {AppLinkedInterface, getAppVersionedSchema} from '../../models/app/app.js'
import {ExtensionSpecification, RemoteAwareExtensionSpecification} from '../../models/extensions/specification.js'
import {JsonSchemaBaseProperties} from '../../utilities/json-schema.js'
import {configurationFileNames} from '../../constants.js'
import {normaliseJsonSchema} from '@shopify/cli-kit/node/json-schema'
import {mkdir, writeFile} from '@shopify/cli-kit/node/fs'
import {joinPath} from '@shopify/cli-kit/node/path'
import {zodToJsonSchema} from 'zod-to-json-schema'

const SCHEMAS_DIRNAME = 'schemas'
const EXTENSIONS_DIRNAME = 'extensions'
const APP_SCHEMA_FILENAME = 'app.schema.json'
const SCHEMA_DESCRIPTION =
  'Generated by `shopify app config validate`. Run validate to refresh. The CLI is the source of truth for validation.'

export interface CachedSchemaIndex {
  /** Absolute path to the app config schema (.shopify/schemas/app.schema.json). */
  appSchemaPath: string
  /** Map of extension spec identifier to absolute path of its cached schema. */
  extensionSchemaByIdentifier: Map<string, string>
}

/**
 * Generate JSON Schema files into `.shopify/schemas/` for the app's main config and every
 * per-extension type known to the linked app. Lets IDE TOML extensions (Taplo / Even Better TOML)
 * offer autocomplete and inline diagnostics that match the CLI's runtime validation.
 *
 * Returns an index mapping each TOML's spec identifier to its cached schema path, so callers
 * (e.g. directive sync) don't have to recompute paths.
 */
export async function writeCachedSchemas(app: AppLinkedInterface): Promise<CachedSchemaIndex> {
  const schemasDir = joinPath(app.directory, configurationFileNames.hiddenFolder, SCHEMAS_DIRNAME)
  const extensionsDir = joinPath(schemasDir, EXTENSIONS_DIRNAME)
  await mkdir(extensionsDir)

  const appSchemaPath = joinPath(schemasDir, APP_SCHEMA_FILENAME)
  const appSchema = await buildAppSchema(app)
  await writeFile(appSchemaPath, stringify(appSchema))

  const extensionSchemaByIdentifier = new Map<string, string>()
  for (const spec of app.specifications) {
    if (spec.uidStrategy === 'single') continue
    const schemaPath = joinPath(extensionsDir, `${spec.identifier}.schema.json`)
    // eslint-disable-next-line no-await-in-loop
    const schema = await buildExtensionSchema(spec)
    // eslint-disable-next-line no-await-in-loop
    await writeFile(schemaPath, stringify(schema))
    extensionSchemaByIdentifier.set(spec.identifier, schemaPath)
  }

  return {appSchemaPath, extensionSchemaByIdentifier}
}

async function buildAppSchema(app: AppLinkedInterface): Promise<Record<string, unknown>> {
  const zodSchema = getAppVersionedSchema(app.specifications, true)
  const jsonSchema = zodToJsonSchema(zodSchema, {target: 'jsonSchema7'}) as Record<string, unknown> & {
    properties?: Record<string, unknown>
    required?: string[]
    description?: string
  }
  jsonSchema.properties ??= {}

  // Each app-config spec (uidStrategy === 'single') may carry a server-authored JSON Schema
  // contract describing its slice of shopify.app.toml. Those contracts live alongside the local
  // Zod definitions and are the authoritative source for fields that exist server-side but
  // haven't been mirrored locally (e.g. fields newly added by the platform). Merge each into
  // the root app schema so autocomplete reflects the full surface, not just what's in Zod.
  for (const spec of app.specifications) {
    if (spec.uidStrategy !== 'single') continue
    const remote = spec.validationSchema?.jsonSchema
    if (!remote) continue
    // eslint-disable-next-line no-await-in-loop
    const contract = (await normaliseJsonSchema(remote)) as {
      properties?: Record<string, unknown>
      required?: string[]
    }
    // Decycle/rebase to the app schema's own root (`#`). For non-circular contracts this is
    // string-equivalent to a deep copy; for circular contracts it converts JS cycles into
    // resolvable `$ref` strings so the final schema can be serialized.
    const cleaned = rebaseAndDecycle(contract, '#') as {properties?: Record<string, unknown>; required?: string[]}
    if (cleaned.properties) {
      // Server contract wins on collision — it reflects what the platform actually validates.
      jsonSchema.properties = {...jsonSchema.properties, ...cleaned.properties}
    }
    if (cleaned.required && cleaned.required.length > 0) {
      jsonSchema.required = Array.from(new Set([...(jsonSchema.required ?? []), ...cleaned.required]))
    }
  }

  // The `[[extensions]]` array in shopify.app.toml is dynamic per-entry — keep it permissive so
  // autocomplete on top-level keys still works without falsely flagging unknown extension fields.
  jsonSchema.properties.extensions = {
    type: 'array',
    items: {type: 'object', additionalProperties: true},
  }

  jsonSchema.description ??= SCHEMA_DESCRIPTION
  return jsonSchema
}

async function buildExtensionSchema(
  spec: ExtensionSpecification | RemoteAwareExtensionSpecification,
): Promise<Record<string, unknown>> {
  const remote = spec.validationSchema?.jsonSchema
  const entry = remote
    ? ((await normaliseJsonSchema(remote)) as Record<string, unknown> & {
        properties?: Record<string, unknown>
        required?: string[]
      })
    : (zodToJsonSchema(spec.schema, {target: 'jsonSchema7'}) as Record<string, unknown> & {
        properties?: Record<string, unknown>
        required?: string[]
      })

  // Match the runtime parser: every extension TOML entry can carry the base fields (`type`,
  // `handle`, `uid`, `path`, `extensions`) regardless of what the spec contract says.
  entry.properties = {...JsonSchemaBaseProperties, ...(entry.properties ?? {})}

  // `api_version` lives at the file root in the modern `[[extensions]]` format (the CLI hoists
  // it from there before validating each entry against the spec contract). Strip it out of the
  // per-entry shape so it isn't falsely required inside `[[extensions]]` blocks.
  const entryWithoutApiVersion = stripApiVersion(entry)

  // The entry schema may carry internal `$ref`s (e.g. `#/properties/extension_points`) that the
  // remote schema authored relative to the spec root, and `normaliseJsonSchema` can also leave
  // raw JavaScript object cycles in place. Park the entry under `definitions/entry`, rebase its refs
  // there, and convert any surviving cycles into resolvable `$ref` strings.
  // Strip `$schema` / `$id` from the entry first — when those metadata fields appear inside a
  // nested subtree some resolvers (including Taplo) treat the subtree as a separate document
  // boundary, which makes our wrapper's rebased `$ref`s resolve against the wrong root.
  const {$schema: _droppedSchema, $id: _droppedId, ...entryWithoutMeta} = entryWithoutApiVersion
  const entryDef = rebaseAndDecycle(entryWithoutMeta, '#/definitions/entry')

  // Extension TOMLs come in two formats — legacy flat (spec fields at the root) and modern
  // (`api_version` at the root + `[[extensions]]` array). Accept either via anyOf so Taplo can
  // surface useful completions for both.
  return {
    definitions: {entry: entryDef},
    anyOf: [
      {$ref: '#/definitions/entry'},
      {
        type: 'object',
        properties: {
          api_version: {type: 'string'},
          extensions: {
            type: 'array',
            items: {$ref: '#/definitions/entry'},
          },
        },
        additionalProperties: true,
      },
    ],
    description: SCHEMA_DESCRIPTION,
  }
}

function stripApiVersion(
  entry: Record<string, unknown> & {properties?: Record<string, unknown>; required?: string[]},
): Record<string, unknown> {
  const {api_version: _omit, ...rest} = entry.properties ?? {}
  const required = (entry.required ?? []).filter((key) => key !== 'api_version')
  return {
    ...entry,
    properties: rest,
    ...(required.length > 0 ? {required} : {}),
  }
}

/**
 * Walk a JSON Schema and produce a copy ready to live at `newRoot` in the wrapper document.
 *
 * Two transforms happen during the walk:
 * 1. **Rebase internal `$ref` strings** from the original document root to `newRoot`. For
 *    example, with `newRoot = "#/definitions/entry"`, a ref of `#/properties/x` becomes
 *    `#/definitions/entry/properties/x`. External refs (`http://...`, `file://...`) are left alone.
 * 2. **Convert JavaScript object cycles to `$ref` strings.** `normaliseJsonSchema` calls
 *    `$RefParser.dereference()`, which replaces some circular refs with real object cycles
 *    rather than leaving them as `$ref` strings. Those cycles would crash `JSON.stringify`,
 *    so when the walker revisits an object it emits a `$ref` to the first-seen path instead.
 *
 * Returns a new object — the input is not mutated.
 */
function rebaseAndDecycle(node: unknown, newRoot: string): Record<string, unknown> {
  // Map object → JSON Pointer path relative to `newRoot` (entry root itself is the empty string).
  const seen = new Map<object, string>()

  const escapePointerSegment = (segment: string): string => segment.replace(/~/g, '~0').replace(/\//g, '~1')

  const walk = (value: unknown, pathSuffix: string): unknown => {
    if (value === null || typeof value !== 'object') return value
    const cached = seen.get(value)
    if (cached !== undefined) {
      return {$ref: cached === '' ? newRoot : `${newRoot}${cached}`}
    }
    seen.set(value, pathSuffix)

    if (Array.isArray(value)) {
      return value.map((item, index) => walk(item, `${pathSuffix}/${index}`))
    }

    const obj = value as Record<string, unknown>
    const result: Record<string, unknown> = {}
    for (const key of Object.keys(obj)) {
      const val = obj[key]
      if (key === '$ref' && typeof val === 'string' && (val === '#' || val.startsWith('#/'))) {
        result.$ref = val === '#' ? newRoot : `${newRoot}${val.slice(1)}`
      } else {
        result[key] = walk(val, `${pathSuffix}/${escapePointerSegment(key)}`)
      }
    }
    return result
  }

  return walk(node, '') as Record<string, unknown>
}

function stringify(schema: Record<string, unknown>): string {
  return `${JSON.stringify(schema, null, 2)}\n`
}
