name: Linting

on:
  push:
    branches: [main]
    paths: ['packages/**']
  pull_request:
    branches: [main]
    paths: ['packages/**']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - uses: actions/setup-node@v1
        name: Setup node.js and yarn
        with:
          node-version: 16.13.1

      - name: Get yarn cache directory
        id: yarn-cache-get-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        name: Restore yarn cache
        with:
          path: ${{ steps.yarn-cache-get-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - uses: actions/cache@v1
        id: eslint-cache
        name: Restore ESLint cache
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Lint
        run: yarn lint --cache
