name: Release

on:
  release:
    types: [created, edited]
  pull_request:
    branches: [main]

jobs:
  releases-matrix:
    name: ${{ github.event_name == 'release' && 'Release' || 'Test packaging of' }} shopify-extensions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: darwin
        include:
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup build toolchain
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Setup ruby
        uses: actions/setup-ruby@v1
      - name: Build node packages
        run: make build-node-packages
      - name: Build and package executable
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make package
      - name: Release
        if: ${{ github.event_name == 'release' }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token && \
          gh release upload `basename ${{ github.ref }}` shopify-extensions-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}.gz && \
          gh release upload `basename ${{ github.ref }}` shopify-extensions-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}.md5
