name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: make test

  integration-test:
    strategy:
      matrix:
        os: [ubuntu-latest] # TODO: currently not working on windows-latest
    name: integration-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
          cache: true
      - run: go mod vendor
      - uses: actions/setup-node@v2
        with:
          node-version: 18.0.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Integration Test
        run: make integration-test
