import {DeployConfig, ReqDeployConfig} from './types.js'
import {gitInit} from '../../prompts/git-init.js'
import {path, git, error} from '@shopify/cli-kit'

export const getDeployConfig = async (config: DeployConfig): Promise<ReqDeployConfig> => {
  const directory = config.path ? path.resolve(config.path) : process.cwd()

  await git.ensurePresentOrAbort()
  await insideGitDirectory(directory)

  const [latestCommit, commitRef] = await Promise.all([
    git.getLatestCommit(directory),
    git.getHeadSymbolicRef(directory),
  ])

  return {
    deploymentToken: config.deploymentToken,
    dmsAddress: config.dmsAddress,
    healthCheck: config.healthCheck,
    commitMessage: config.commitMessage ?? latestCommit.message,
    commitAuthor: config.commitAuthor ?? latestCommit.author_name,
    commitSha: latestCommit.hash,
    commitRef,
    timestamp: latestCommit.date,
    path: directory,
  }
}

const insideGitDirectory = async (directory: string) => {
  try {
    await git.ensureInsideGitDirectory(directory)
  } catch (err: unknown) {
    if ((err as error.Abort)?.message !== git.OutsideGitDirectoryError().message) throw error

    const shouldGitInit = await gitInit()

    if (!shouldGitInit) throw new error.AbortSilent()

    await git.initializeRepository(directory)
    git.createGitIgnore(directory, git.GitIgnoreTemplate.Hydrogen)
    await git.commitAll('Initial commit generated by deploy-hydrogen', {directory})
  }
}
