// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'App configuration',
  description: 'Reference for the shopify.app.toml configuration file.',
  overviewPreviewDescription: 'shopify.app.toml configuration reference.',
  type: 'resource',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'shopify.app.toml',
          code: './examples/app-configuration.example.toml',
          language: 'toml',
        },
      ],
      title: 'Example configuration',
    },
  },
  definitions: [
  {
    title: 'Global',
    description: 'Global properties.',
    type: 'global',
  },
  {
    title: 'App access',
    description: 'App access properties.',
    type: 'appaccess',
  },
  {
    title: 'Imperative Webhooks Api Version',
    description: 'Imperative Webhooks Api Version properties.',
    type: 'webhooks',
  },
  {
    title: 'App Proxy',
    description: 'App Proxy properties.',
    type: 'appproxy',
  },
  {
    title: 'Point Of Sale Configuration',
    description: 'Point Of Sale Configuration properties.',
    type: 'pointofsale',
  },
  {
    title: 'App Home',
    description: 'App Home properties.',
    type: 'apphome',
  },
  {
    title: 'Channel Configuration',
    description: 'Channel Configuration properties.',
    type: 'channelconfig',
  },
  {
    title: 'Customer Authentication',
    description: 'Customer Authentication properties.',
    type: 'customerauthentication',
  },
  {
    title: 'Custom data',
    description: 'Custom data properties.',
    type: 'data',
  },
  ],
  category: 'app-configuration',
  related: [],
}

export default data