// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'Editor extension collection',
  description: 'Configuration reference for Editor extension collection.',
  overviewPreviewDescription: 'Editor extension collection TOML configuration.',
  type: 'resource',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'shopify.extension.toml',
          code: './examples/editor-extension-collection.example.toml',
          language: 'toml',
        },
      ],
      title: 'Example configuration',
    },
  },
  definitions: [
  {
    title: 'Properties',
    description: 'The following properties are available:',
    type: 'editorextensioncollection',
  },
  ],
  category: 'extension-configuration',
  related: [],
}

export default data