// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'Payments Extension',
  description: 'Configuration reference for Payments Extension.',
  overviewPreviewDescription: 'Payments Extension TOML configuration.',
  type: 'resource',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'shopify.extension.toml',
          code: './examples/payments-extension.example.toml',
          language: 'toml',
        },
      ],
      title: 'Example configuration',
    },
  },
  definitions: [
  ],
  category: 'extension-configuration',
  related: [],
}

export default data