// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'UI Extension',
  description: 'Configuration reference for UI Extension.',
  overviewPreviewDescription: 'UI Extension TOML configuration.',
  type: 'resource',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'shopify.extension.toml',
          code: './examples/ui-extension.example.toml',
          language: 'toml',
        },
      ],
      title: 'Example configuration',
    },
  },
  definitions: [
  {
    title: 'Properties',
    description: 'The following properties are available:',
    type: 'uiextension',
  },
  ],
  category: 'extension-configuration',
  related: [],
}

export default data