import {submissionTraceFixture} from './fixtures/submission-trace.js'
import {buildSubmission, SUBMISSION_SCHEMA_VERSION} from '../submission/index.js'
import {validateTrace} from '../trace/index.js'
import {readFile} from '@shopify/cli-kit/node/fs'
import {joinPath, moduleDirectory} from '@shopify/cli-kit/node/path'
import {describe, expect, test} from 'vitest'
import type {AppSecuritySubmission, BuildSubmissionOptions} from '../submission/index.js'

const fixturesDirectory = joinPath(moduleDirectory(import.meta.url), 'fixtures')

async function jsonFixture<T>(name: string): Promise<T> {
  return JSON.parse(await readFile(joinPath(fixturesDirectory, name))) as T
}

const options: BuildSubmissionOptions = {
  cliVersion: '3.99.0',
  submittedAt: '2026-09-01T09:30:00.000Z',
  versionTag: 'v1.2.3',
  feedback: 'The result for /Users/example/app included AKIA1234567890ABCDEF inaccurately.',
}

describe('buildSubmission', () => {
  test('validates the source fixture before mapping and matches the independently pinned golden payload', async () => {
    // This assertion must run before buildSubmission so a malformed fixture cannot
    // make mapper expectations look correct. The golden file is hand-pinned and
    // must never be generated by buildSubmission.
    expect(validateTrace(structuredClone(submissionTraceFixture))).toEqual({valid: true, errors: []})
    const expected = await jsonFixture<AppSecuritySubmission>('submission.json')

    expect(expected.schemaVersion).toBe(SUBMISSION_SCHEMA_VERSION)
    expect(buildSubmission(structuredClone(submissionTraceFixture), options)).toEqual(expected)
  })

  test('emits a null version tag when no app version is supplied', () => {
    const submission = buildSubmission(structuredClone(submissionTraceFixture), {
      cliVersion: '3.99.0',
      submittedAt: '2026-09-01T09:30:00.000Z',
    })

    expect(submission.report.metadata).toEqual({version_tag: null})
    expect(submission.report.feedback).toBeNull()
  })

  test('does not serialize the fixture’s excluded structural fields or unknown sentinels', async () => {
    const forbiddenValues = await jsonFixture<string[]>('submission-forbidden-values.json')
    const serialized = JSON.stringify(buildSubmission(structuredClone(submissionTraceFixture), options))

    for (const forbiddenValue of forbiddenValues) expect(serialized).not.toContain(forbiddenValue)
  })

  test('applies a second redaction pass to every free-text output field', () => {
    const secret = 'AKIA1234567890ABCDEF'
    const trace = structuredClone(submissionTraceFixture)
    const mutableEngine = trace.engine as unknown as Record<string, string>
    mutableEngine.name = `engine-${secret}`
    mutableEngine.version = `version-${secret}`
    mutableEngine.ruleset = `ruleset-${secret}`
    trace.findings[0]!.title = `Unsafe HTML assignment: ${secret}`

    const submission = buildSubmission(trace, {
      cliVersion: '3.99.0',
      submittedAt: '2026-09-01T09:30:00.000Z',
      versionTag: `version-${secret}`,
    })
    const serialized = JSON.stringify(submission)

    expect(serialized).not.toContain(secret)
    expect(submission.report.findings[0]!.title).toContain('[REDACTED:20]')
    expect(submission.report.metadata.version_tag).toContain('[REDACTED:20]')
  })

  test('preserves feedback exactly without applying the free-text redactor', () => {
    const feedback = 'The result for /Users/example/app included AKIA1234567890ABCDEF inaccurately.'

    const submission = buildSubmission(structuredClone(submissionTraceFixture), {...options, feedback})

    expect(submission.report.feedback).toBe(feedback)
  })
})
