// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app deploy',
  description: `[Builds the app](https://shopify.dev/docs/apps/tools/cli/commands#build) and deploys app extensions.

  When you run this command, Shopify CLI creates an app version that contains a snapshot of all of your app extensions, including the app extensions that you manage in the Partner Dashboard, and releases the app version to users.

  This command doesn't deploy your [web app](https://shopify.dev/docs/apps/tools/cli/structure#web-components). When you're ready to deploy your app, you need to deploy these components to your own hosting solution. [Learn more about deploying your web app](https://shopify.dev/docs/apps/deployment/web).
  `,
  overviewPreviewDescription: `Deploy your Shopify app.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app deploy',
          code: './examples/app-deploy.example.sh',
          language: 'bash',
        },
      ],
      title: 'app deploy',
    },
  },
  definitions: [
    
  {
    title: 'Flags',
    description: 'The following flags are available for the `app deploy` command:',
    type: 'appdeploy',
  },
  ],
  category: 'Commands',
  subCategory: 'app',
  related: [
  ],
}

export default data