name: shopify-cli-extensions

type: go

up:
  - ruby:
      version: '3.1.2'
  - python:
      version: '3.9.10'
  - go:
      version: 1.17.6
      modules: true
  - node:
      version: v18.0.0
      yarn: v1.22.18
  - homebrew:
    - delve

