#!/usr/bin/env node

/**
 * Embeds the versioned semantic-check markdown so the bundled CLI does not
 * depend on runtime assets. The markdown files remain the source of truth.
 */
import {readFileSync, readdirSync, writeFileSync} from 'node:fs'
import {dirname, join} from 'node:path'
import {fileURLToPath} from 'node:url'

const engineRoot = dirname(fileURLToPath(import.meta.url))
const checksDirectory = join(engineRoot, 'checks')
const outputPath = join(checksDirectory, 'embedded.ts')
const files = readdirSync(checksDirectory)
  .filter((file) => file.endsWith('.md'))
  .sort()
const sources = files.map((file) => readFileSync(join(checksDirectory, file), 'utf8'))

const output = `// AUTO-GENERATED by app-doctor-engine/embed-checks.mjs — do not edit.
// Source of truth: adjacent checks/*.md files.

// prettier-ignore
export const EMBEDDED_CHECK_SOURCES: readonly string[] = ${JSON.stringify(sources, null, 2)};
`

writeFileSync(outputPath, output)
console.log(`Embedded ${files.length} semantic checks in app-doctor-engine/checks/embedded.ts`)
