/* eslint-disable @shopify/strict-component-boundaries */

/**
 * Embeds the versioned semantic-check markdown so the bundled CLI does not
 * depend on runtime assets. The markdown files remain the source of truth.
 *
 *   node embed-checks.mjs           Write checks/embedded.ts
 *   node embed-checks.mjs --check   Exit 1 if embedded.ts is stale
 */
import {readFileSync, readdirSync, writeFileSync} from 'node:fs'
import {dirname, join} from 'node:path'
import {fileURLToPath} from 'node:url'

const engineRoot = dirname(fileURLToPath(import.meta.url))
const checksDirectory = join(engineRoot, 'checks')
const instructionsPath = join(engineRoot, 'INSTRUCTIONS.md')
const outputPath = join(checksDirectory, 'embedded.ts')
const files = readdirSync(checksDirectory)
  .filter((file) => file.endsWith('.md'))
  .sort()
const sources = files.map((file) => readFileSync(join(checksDirectory, file), 'utf8'))
const instructions = readFileSync(instructionsPath, 'utf8')

const output = `// AUTO-GENERATED by app-doctor-engine/embed-checks.mjs — do not edit.
// Sources of truth: adjacent checks/*.md files and ../INSTRUCTIONS.md.
/* eslint-disable no-restricted-syntax, no-template-curly-in-string */

// prettier-ignore
export const EMBEDDED_CHECK_SOURCES: ReadonlyArray<string> = ${JSON.stringify(sources, null, 2)};

// prettier-ignore
export const EMBEDDED_APP_DOCTOR_INSTRUCTIONS = ${JSON.stringify(instructions)};
`

const args = process.argv.slice(2)
const unknownArgs = args.filter((arg) => arg !== '--check')

if (unknownArgs.length > 0) {
  console.error(`Unknown argument${unknownArgs.length === 1 ? '' : 's'}: ${unknownArgs.join(', ')}

Usage:
  node embed-checks.mjs           Write checks/embedded.ts
  node embed-checks.mjs --check   Exit 1 if embedded.ts is stale`)
  process.exitCode = 1
} else if (args.includes('--check')) {
  let actual = ''
  try {
    actual = readFileSync(outputPath, 'utf8')
  } catch (error) {
    if (error.code !== 'ENOENT') throw error
    // Missing generated file is a mismatch.
  }

  if (actual === output) {
    console.log(`App Doctor embedded.ts is up to date (${files.length} semantic checks and instructions)`)
  } else {
    console.error(`App Doctor embedded.ts is out of date.

Markdown checks and instructions are the source of truth, but
packages/app/src/cli/services/app-doctor-engine/checks/embedded.ts
does not match what embed-checks.mjs would generate.

Run:
  pnpm --filter @shopify/app generate:app-doctor-checks

Then commit the updated embedded.ts.`)
    process.exitCode = 1
  }
} else {
  writeFileSync(outputPath, output)
  console.log(
    `Embedded ${files.length} semantic checks and App Doctor instructions in app-doctor-engine/checks/embedded.ts`,
  )
}
