// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app config push',
  description: `Pushes your default app configuration to Shopify. You can specify a different configuration file with the \`--config\` flag. This overwrites the settings for the app specified in the configuration file in your Partner Dashboard.`,
  overviewPreviewDescription: `Pushes your default app configuration to Shopify.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app config push',
          code: './examples/app-config-push.example.sh',
          language: 'bash',
        },
      ],
      title: 'app config push',
    },
  },
  definitions: [
    
  {
    title: 'Flags',
    description: 'The following flags are available for the `app config push` command:',
    type: 'appconfigpush',
  },
  ],
  category: 'Commands',
  subCategory: 'app',
  related: [
  ],
}

export default data