// This is an autogenerated file. Don't edit this file manually.
import {ReferenceEntityTemplateSchema} from '@shopify/generate-docs'

const data: ReferenceEntityTemplateSchema = {
  name: 'app update-url',
  description: `Updates the app URL and allowed redirection URLs for your app. When you specify URLs using this command, the current URLs are overwritten.

  Your current app URLs are provided as placeholder responses. To keep either your app URL or redirect URLs the same, submit the placeholder content. Alternatively, use the \`--app-url\` or \`--redirect-urls\` flag to update only one of these settings.`,
  overviewPreviewDescription: `Update your app and redirect URLs in the Partners Dashboard.`,
  type: 'command',
  isVisualComponent: false,
  defaultExample: {
    codeblock: {
      tabs: [
        {
          title: 'app update-url',
          code: './examples/app-update-url.example.sh',
          language: 'bash',
        },
      ],
      title: 'app update-url',
    },
  },
  definitions: [
    
  {
    title: 'Flags',
    description: 'The following flags are available for the `app update-url` command:',
    type: 'appupdateurl',
  },
  ],
  category: 'Commands',
  subCategory: 'app',
  related: [
  ],
}

export default data