name: 'Setup CLI deps'
description: 'Sets up dependencies necessary for cli'
inputs:
  node-version:
    required: true
    description: 'Node version'
runs:
  using: 'composite'
  steps:
    - name: Set Git configuration
      run: |
        git config --global user.email "app-management@shopify.com"
        git config --global user.name "App Management"
      shell: bash
    - name: Install pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash
