name: "Setup CLI deps"
description: "Sets up dependencies necessary for cli"
inputs:
  node-version:
    required: true
    description: "Node version"
runs:
  using: "composite"
  steps:
    - name: Set Git configuration
      run: |
        git config --global user.email "cli-foundations@shopify.com"
        git config --global user.name "CLI Foundations"
      shell: bash
    - name: Set Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Install Bundler
      run: gem install bundler -v ${{ env.BUNDLER_VERSION }}
      shell: bash
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version:  ${{ env.PNPM_VERSION }}
    - name: Install yarn
      run: npm install --global yarn@${{ env.YARN_VERSION }}
      shell: bash
    - name: Increase yarn timeout
      run: yarn config set network-timeout 300000
      shell: bash
    - name: Install dependencies
      run: yarn install --ignore-engines
      shell: bash
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2.2.5
