name: "Setup CLI deps"
description: "Sets up dependencies necessary for cli"
inputs:
  node-version:
    required: true
    description: "Node version"
runs:
  using: "composite"
  steps:
    - name: Set Git configuration
      run: |
        git config --global user.email "cli-foundations@shopify.com"
        git config --global user.name "CLI Foundations"
      shell: bash
    - name: Set Ruby
      uses: ruby/setup-ruby@8df78e55761745aad83acaf3ff12976382356e6d # pin@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: false
    - name: Install Bundler
      run: gem install bundler -v ${{ env.BUNDLER_VERSION }}
      shell: bash
    - name: Install Bundler dependencies
      working-directory: packages/cli-kit/assets/cli-ruby
      run: bundle install
      shell: bash
    - name: Install pnpm
      uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d # pin@v2.2.2
      with:
        version: ${{ env.PNPM_VERSION }}
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Install yarn
      run: npm install --global yarn@${{ env.YARN_VERSION }}
      shell: bash
    - name: Increase yarn timeout
      run: yarn config set network-timeout 300000
      shell: bash
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@526caa9cb6b172df606cd33b7a3544bf1bc49c2e # pin@v2.2.5
