[package]
name = "toml_patch"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
toml_edit = "0.22.24"
wasm-bindgen = "0.2.89"
wee_alloc = "0.4.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
