// This is an autogenerated file. Don't edit this file manually.
export interface appconfiglink {
  /**
   * The Client ID of your app.
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   */
  '-c, --config <value>'?: string

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * The path to your app directory.
   */
  '--path <value>'?: string

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''
}
