// This is an autogenerated file. Don't edit this file manually.
export interface appdeploy {
  /**
   * The Client ID of your app.
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   */
  '-c, --config <value>'?: string

  /**
   * Deploy without asking for confirmation.
   */
  '-f, --force'?: ''

  /**
   * Optional message that will be associated with this version. This is for internal use only and won't be available externally.
   */
  '--message <value>'?: string

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * Creates a version but doesn't release it - it's not made available to merchants.
   */
  '--no-release'?: ''

  /**
   * The path to your app directory.
   */
  '--path <value>'?: string

  /**
   * Reset all your settings.
   */
  '--reset'?: ''

  /**
   * URL associated with the new app version.
   */
  '--source-control-url <value>'?: string

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''

  /**
   * Optional version tag that will be associated with this app version. If not provided, an auto-generated identifier will be generated for this app version.
   */
  '--version <value>'?: string
}
