// This is an autogenerated file. Don't edit this file manually.
export interface appenvpull {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * Specify an environment file to update if the update flag is set
   * @environment SHOPIFY_FLAG_ENV_FILE
   */
  '--env-file <value>'?: string
}
