// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `app config use` command:
 * @publicDocs
 */
export interface appconfiguse {
  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
