// This is an autogenerated file. Don't edit this file manually.
export interface appenvpull {
  /**
   * The name of the app configuration.
   */
  '-c, --config <value>'?: string

  /**
   * Specify an environment file to update if the update flag is set
   */
  '--env-file <value>'?: string

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * The path to your app directory.
   */
  '--path <value>'?: string

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''
}
