// This is an autogenerated file. Don't edit this file manually.
export interface apprelease {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * [Deprecated] Release without asking for confirmation. Equivalent to --allow-updates --allow-deletes. Use --allow-updates for CI/CD environments instead.
   * @environment SHOPIFY_FLAG_FORCE
   */
  '-f, --force'?: ''

  /**
   * Allows adding and updating extensions and configuration without requiring user confirmation. Recommended option for CI/CD environments.
   * @environment SHOPIFY_FLAG_ALLOW_UPDATES
   */
  '--allow-updates'?: ''

  /**
   * Allows removing extensions and configuration without requiring user confirmation. For CI/CD environments, the recommended flag is --allow-updates.
   * @environment SHOPIFY_FLAG_ALLOW_DELETES
   */
  '--allow-deletes'?: ''

  /**
   * The name of the app version to release.
   * @environment SHOPIFY_FLAG_VERSION
   */
  '--version <value>': string
}
