// This is an autogenerated file. Don't edit this file manually.
export interface appdev {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * Store URL. Must be an existing development or Shopify Plus sandbox store.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * Skips the installation of dependencies. Deprecated, use workspaces instead.
   * @environment SHOPIFY_FLAG_SKIP_DEPENDENCIES_INSTALLATION
   */
  '--skip-dependencies-installation'?: ''

  /**
   * Uses the app URL from the toml file instead an autogenerated URL for dev.
   * @environment SHOPIFY_FLAG_NO_UPDATE
   */
  '--no-update'?: ''

  /**
   * Resource URL for subscription UI extension. Format: "/products/{productId}"
   * @environment SHOPIFY_FLAG_SUBSCRIPTION_PRODUCT_URL
   */
  '--subscription-product-url <value>'?: string

  /**
   * Resource URL for checkout UI extension. Format: "/cart/{productVariantID}:{productQuantity}"
   * @environment SHOPIFY_FLAG_CHECKOUT_CART_URL
   */
  '--checkout-cart-url <value>'?: string

  /**
   * Use a custom tunnel, it must be running before executing dev. Format: "https://my-tunnel-url:port".
   * @environment SHOPIFY_FLAG_TUNNEL_URL
   */
  '--tunnel-url <value>'?: string

  /**
   * Service entry point will listen to localhost. A tunnel won't be used. Will work for testing many app features, but not those that directly invoke your app (E.g: Webhooks)
   * @environment SHOPIFY_FLAG_USE_LOCALHOST
   */
  '--use-localhost'?: ''

  /**
   * Port to use for localhost.
   * @environment SHOPIFY_FLAG_LOCALHOST_PORT
   */
  '--localhost-port <value>'?: string

  /**
   * Theme ID or name of the theme app extension host theme.
   * @environment SHOPIFY_FLAG_THEME
   */
  '-t, --theme <value>'?: string

  /**
   * Local port of the theme app extension development server.
   * @environment SHOPIFY_FLAG_THEME_APP_EXTENSION_PORT
   */
  '--theme-app-extension-port <value>'?: string

  /**
   * The file path or URL. The file path is to a file that you want updated on idle. The URL path is where you want a webhook posted to report on file changes.
   * @environment SHOPIFY_FLAG_NOTIFY
   */
  '--notify <value>'?: string
}
