// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `app config link` command:
 * @publicDocs
 */
export interface appconfiglink {
  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * The name of the app configuration file to create or overwrite.
   * @environment SHOPIFY_FLAG_APP_CONFIG_FILE_NAME
   */
  '--file-name <value>'?: string

  /**
   * Overwrite an existing configuration file without prompting.
   * @environment SHOPIFY_FLAG_FORCE
   */
  '--force'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
