// This is an autogenerated file. Don't edit this file manually.
export interface appgenerateschema {
  /**
   * The Client ID to fetch the schema with.
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   */
  '-c, --config <value>'?: string

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * The path to your function directory.
   */
  '--path <value>'?: string

  /**
   * Output the schema to stdout instead of writing to a file.
   */
  '--stdout'?: ''

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''
}
