// This is an autogenerated file. Don't edit this file manually.
/**
 * The information returned includes the following:
 * 
 *   - The app and dev store that's used when you run the [dev](/docs/api/shopify-cli/app/app-dev) command. You can reset these configurations using [`dev --reset`](/docs/api/shopify-cli/app/app-dev#flags-propertydetail-reset).
 *   - The [structure](/docs/apps/tools/cli/structure) of your app project.
 *   - The [access scopes](/docs/api/usage) your app has requested.
 *   - System information, including the package manager and version of Shopify CLI used in the project.
 * @publicDocs
 */
export interface appinfo {
  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * Outputs environment variables necessary for running and deploying web/.
   * @environment SHOPIFY_FLAG_OUTPUT_WEB_ENV
   */
  '--web-env'?: ''
}
