// This is an autogenerated file. Don't edit this file manually.
/**
 * Validates the selected app configuration file and all extension configurations against their schemas and reports any errors found.
 * @publicDocs
 */
export interface appconfigvalidate {
  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
