// This is an autogenerated file. Don't edit this file manually.
/**
 * The information returned includes the following:
 * 
 *   - The function handle
 *   - The function name
 *   - The function API version
 *   - The targeting configuration
 *   - The schema path
 *   - The WASM path
 *   - The function runner path
 * @publicDocs
 */
export interface appfunctioninfo {
  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path to your function directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
