// This is an autogenerated file. Don't edit this file manually.
export interface appinit {
  /**
   * Which flavor of the given template to use.
   */
  '--flavor <value>'?: string

  /**
   * 
   */
  '-n, --name <value>'?: string

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * 
   */
  '-d, --package-manager <value>'?: string

  /**
   * 
   */
  '-p, --path <value>'?: string

  /**
   * The app template. Accepts one of the following:
       - <remix|none>
       - Any GitHub repo with optional branch and subpath, e.g., https://github.com/Shopify/<repository>/[subpath]#[branch]
   */
  '--template <value>'?: string

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''
}
