// This is an autogenerated file. Don't edit this file manually.
export interface apprelease {
  /**
   * The Client ID of your app.
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   */
  '-c, --config <value>'?: string

  /**
   * Release without asking for confirmation.
   */
  '-f, --force'?: ''

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * The path to your app directory.
   */
  '--path <value>'?: string

  /**
   * Reset all your settings.
   */
  '--reset'?: ''

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''

  /**
   * The name of the app version to release.
   */
  '--version <value>': string
}
