// This is an autogenerated file. Don't edit this file manually.
export interface appfunctionfixtureoverride {
  /**
   * Path to JSON config file containing source, target, and overrides
   *
   */
  '-c, --config <value>'?: string

  /**
   * Show CLI help.
   *
   */
  '-h, --help'?: ''

  /**
   * Run in interactive mode to build overrides step by step
   *
   */
  '-i, --interactive'?: ''

  /**
   * JSON string of overrides (e.g., '{"input.cart.lines.0.quantity": 5}')
   *
   */
  '-o, --overrides <value>'?: string

  /**
   * Path to the function extension
   *
   */
  '-p, --path <value>': string

  /**
   * Source fixture name (without .json extension)
   *
   */
  '-s, --source <value>'?: string

  /**
   * Target fixture name (without .json extension)
   *
   */
  '-t, --target <value>'?: string
}
