// This is an autogenerated file. Don't edit this file manually.
export interface appexecute {
  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The file name where results should be written, instead of STDOUT.
   * @environment SHOPIFY_FLAG_OUTPUT_FILE
   */
  '--output-file <value>'?: string

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * The GraphQL query or mutation, as a string.
   * @environment SHOPIFY_FLAG_QUERY
   */
  '-q, --query <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * The myshopify.com domain of the store to execute against. The app must be installed on the store. If not specified, you will be prompted to select a store.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * The values for any GraphQL variables in your query or mutation, in JSON format.
   * @environment SHOPIFY_FLAG_VARIABLES
   */
  '-v, --variables <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The API version to use for the query or mutation. Defaults to the latest stable version.
   * @environment SHOPIFY_FLAG_VERSION
   */
  '--version <value>'?: string
}
