// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `app graphiql` command:
 * @publicDocs
 */
export interface appgraphiql {
  /**
   * The Client ID of your app.
   * @environment SHOPIFY_FLAG_CLIENT_ID
   */
  '--client-id <value>'?: string

  /**
   * The name of the app configuration.
   * @environment SHOPIFY_FLAG_APP_CONFIG
   */
  '-c, --config <value>'?: string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path to your app directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Local port for the GraphiQL server. Must be between 1 and 65535.
   * @environment SHOPIFY_FLAG_PORT
   */
  '--port <value>'?: string

  /**
   * Reset all your settings.
   * @environment SHOPIFY_FLAG_RESET
   */
  '--reset'?: ''

  /**
   * The myshopify.com domain of the store to open GraphiQL against. The app must be installed on the store. If not specified, you will be prompted to select a store.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * The values for any GraphQL variables in your query or mutation, in JSON format.
   * @environment SHOPIFY_FLAG_VARIABLES
   */
  '-v, --variables <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The API version to use in GraphiQL. Defaults to the latest stable version.
   * @environment SHOPIFY_FLAG_VERSION
   */
  '--version <value>'?: string
}
