// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `auth status` command:
 * @publicDocs
 */
export interface authstatus {
  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''
}
