// This is an autogenerated file. Don't edit this file manually.
export interface authlogin {
  /**
   * An alias to identify the session.
   * @environment SHOPIFY_FLAG_AUTH_ALIAS
   */
  '--alias <value>'?: string
}
