// This is an autogenerated file. Don't edit this file manually.
export interface authlogin {
  /**
   * Alias of the session you want to login to.
   * @environment SHOPIFY_FLAG_AUTH_ALIAS
   */
  '--alias <value>'?: string
}
