// This is an autogenerated file. Don't edit this file manually.
export interface commands {
  /**
   * Only show provided columns (comma-separated).
   *
   */
  '-c, --columns <value>'?: string

  /**
   * Show deprecated commands.
   *
   */
  '--deprecated'?: ''

  /**
   * Show extra columns.
   *
   */
  '-x, --extended'?: ''

  /**
   * Show hidden commands.
   *
   */
  '--hidden'?: ''

  /**
   * Format output as json.
   *
   */
  '--json'?: ''

  /**
   * Do not truncate output.
   *
   */
  '--no-truncate'?: ''

  /**
   * Property to sort by.
   *
   */
  '--sort <value>'?: string

  /**
   * Show tree of commands.
   *
   */
  '--tree'?: ''
}
