// This is an autogenerated file. Don't edit this file manually.
export interface commands {
  /**
   * only show provided columns (comma-separated)
   *
   */
  '--columns <value>'?: string

  /**
   * output is csv format [alias: --output=csv]
   *
   */
  '--csv'?: ''

  /**
   * show deprecated commands
   *
   */
  '--deprecated'?: ''

  /**
   * show extra columns
   *
   */
  '-x, --extended'?: ''

  /**
   * filter property by partial string matching, ex: name=foo
   *
   */
  '--filter <value>'?: string

  /**
   * Show CLI help.
   *
   */
  '-h, --help'?: ''

  /**
   * show hidden commands
   *
   */
  '--hidden'?: ''

  /**
   * Format output as json.
   *
   */
  '--json'?: ''

  /**
   * hide table header from output
   *
   */
  '--no-header'?: ''

  /**
   * do not truncate output to fit screen
   *
   */
  '--no-truncate'?: ''

  /**
   * output in a more machine friendly format
   *
   */
  '--output <value>'?: string

  /**
   * property to sort by (prepend '-' for descending)
   *
   */
  '--sort <value>'?: string

  /**
   * show tree of commands
   *
   */
  '--tree'?: ''
}
