// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `config autocorrect off` command:
 * @publicDocs
 */
export interface configautocorrectoff {

}
