// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `doc fetch` command:
 * @publicDocs
 */
export interface docfetch {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Write the document to this file path instead of printing it to stdout.
   * @environment SHOPIFY_FLAG_OUTPUT
   */
  '-o, --output <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
