// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `fetch-doc` command:
 * @publicDocs
 */
export interface fetchdoc {
  /**
   * The Accept content type to request (defaults to text/markdown).
   * @environment SHOPIFY_FLAG_CONTENT_TYPE
   */
  '--content-type <value>'?: string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
