// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `fetch-doc` command:
 * @publicDocs
 */
export interface fetchdoc {
  /**
   * The Accept content type to request (defaults to text/markdown).
   * @environment SHOPIFY_FLAG_CONTENT_TYPE
   */
  '--content-type <value>'?: string
}
