// This is an autogenerated file. Don't edit this file manually.
export interface help {
  /**
   * Include all nested commands in the output.
   * @environment SHOPIFY_FLAG_CLI_NESTED_COMMANDS
   */
  '-n, --nested-commands'?: ''
}
