// This is an autogenerated file. Don't edit this file manually.
export interface hydrogengenerateroute {
  /**
   * Remix adapter used in the route. The default is `@shopify/remix-oxygen`.
   */
  '--adapter <value>'?: string

  /**
   * Generate TypeScript files
   */
  '--typescript'?: ''

  /**
   * The param name in Remix routes for the i18n locale, if any. Example: `locale` becomes ($locale).
   */
  '--locale-param <value>'?: string

  /**
   * Overwrites the destination directory and files if they already exist.
   */
  '-f, --force'?: ''

  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   */
  '--path <value>'?: string
}
