// This is an autogenerated file. Don't edit this file manually.
/**
 * Links your local development environment to a remote Hydrogen storefront. You can link an unlimited number of development environments to a single Hydrogen storefront.
 * 
 *   Linking to a Hydrogen storefront enables you to run [dev](/docs/api/shopify-cli/hydrogen/hydrogen-dev) and automatically inject your linked Hydrogen storefront's environment variables directly into the server runtime.
 * 
 *   After you run the `link` command, you can access the [env list](/docs/api/shopify-cli/hydrogen/hydrogen-env-list), [env pull](/docs/api/shopify-cli/hydrogen/hydrogen-env-pull), and [unlink](/docs/api/shopify-cli/hydrogen/hydrogen-unlink) commands.
 * @publicDocs
 */
export interface hydrogenlink {
  /**
   * Overwrites the destination directory and files if they already exist.
   * @environment SHOPIFY_HYDROGEN_FLAG_FORCE
   */
  '-f, --force'?: ''

  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   * @environment SHOPIFY_HYDROGEN_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * The name of a Hydrogen Storefront (e.g. "Jane's Apparel")
   * @environment SHOPIFY_HYDROGEN_STOREFRONT
   */
  '--storefront <value>'?: string
}
