// This is an autogenerated file. Don't edit this file manually.
export interface hydrogensetupcss {
  /**
   * Overwrites the destination directory and files if they already exist.
   * @environment SHOPIFY_HYDROGEN_FLAG_FORCE
   */
  '-f, --force'?: ''

  /**
   * Auto installs dependencies using the active package manager.
   * @environment SHOPIFY_HYDROGEN_FLAG_INSTALL_DEPS
   */
  '--install-deps'?: ''

  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   * @environment SHOPIFY_HYDROGEN_FLAG_PATH
   */
  '--path <value>'?: string
}
