// This is an autogenerated file. Don't edit this file manually.
export interface hydrogendevvite {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   */
  '--path <value>'?: string

  /**
   * Entry file for the worker. Defaults to `./server`.
   */
  '--entry <value>'?: string

  /**
   * The port to run the server on. Defaults to 3000.
   */
  '--port <value>'?: string

  /**
   * Automatically generates GraphQL types for your project’s Storefront API queries.
   */
  '--codegen'?: ''

  /**
   * Specifies a path to a codegen configuration file. Defaults to `<root>/codegen.ts` if this file exists.
   */
  '--codegen-config-path <value>'?: string

  /**
   * Disable rendering fallback routes when a route file doesn't exist.
   */
  '--disable-virtual-routes'?: ''

  /**
   * Enables inspector connections to the server with a debugger such as Visual Studio Code or Chrome DevTools.
   */
  '--debug'?: ''

  /**
   * The port where the inspector is available. Defaults to 9229.
   */
  '--inspector-port <value>'?: string

  /**
   * Expose the server to the network
   */
  '--host'?: ''

  /**
   * Specifies the environment to pull variables from using its Git branch name.
   */
  '-e, --env-branch <value>'?: string

  /**
   * Skip the version check when running `hydrogen dev`
   */
  '--disable-version-check'?: ''
}
