// This is an autogenerated file. Don't edit this file manually.
/**
 * Creates a global h2 shortcut for Shopify CLI using shell aliases.
 * 
 *   The following shells are supported:
 * 
 *   - Bash (using `~/.bashrc`)
 *   - ZSH (using `~/.zshrc`)
 *   - Fish (using `~/.config/fish/functions`)
 *   - PowerShell (added to `$PROFILE`)
 * 
 *   After the alias is created, you can call Shopify CLI from anywhere in your project using `h2 <command>`.
 * @publicDocs
 */
export interface hydrogenshortcut {

}
