// This is an autogenerated file. Don't edit this file manually.
export interface hydrogenbuildvite {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   */
  '--path <value>'?: string

  /**
   * Entry file for the worker. Defaults to `./server`.
   */
  '--entry <value>'?: string

  /**
   * Controls whether sourcemaps are generated. Default to `true`. Deactivate `--no-sourcemaps`.
   */
  '--sourcemap'?: ''

  /**
   * Checks that there is exactly one valid lockfile in the project. Defaults to `true`. Deactivate with `--no-lockfile-check`.
   */
  '--lockfile-check'?: ''

  /**
   * Disables any warnings about missing standard routes.
   */
  '--disable-route-warning'?: ''

  /**
   * Automatically generates GraphQL types for your project’s Storefront API queries.
   */
  '--codegen'?: ''

  /**
   * Specifies a path to a codegen configuration file. Defaults to `<root>/codegen.ts` if this file exists.
   */
  '--codegen-config-path <value>'?: string
}
