// This is an autogenerated file. Don't edit this file manually.
/**
 * Lists all environments available on the linked Hydrogen storefront.
 * @publicDocs
 */
export interface hydrogenenvlist {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   * @environment SHOPIFY_HYDROGEN_FLAG_PATH
   */
  '--path <value>'?: string
}
