// This is an autogenerated file. Don't edit this file manually.
export interface hydrogencheck {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   */
  '--path <value>'?: string
}
