// This is an autogenerated file. Don't edit this file manually.
export interface hydrogenlink {
  /**
   * Overwrites the destination directory and files if they already exist.
   */
  '-f, --force'?: ''

  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   */
  '--path <value>'?: string

  /**
   * The name of a Hydrogen Storefront (e.g. "Jane's Apparel")
   */
  '--storefront <value>'?: string
}
