// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `hydrogen unlink` command:
 * @publicDocs
 */
export interface hydrogenunlink {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   * @environment SHOPIFY_HYDROGEN_FLAG_PATH
   */
  '--path <value>'?: string
}
