// This is an autogenerated file. Don't edit this file manually.
export interface hydrogensetup {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   */
  '--path <value>'?: string

  /**
   * Overwrites the destination directory and files if they already exist.
   */
  '-f, --force'?: ''

  /**
   * Sets the styling strategy to use. One of `tailwind`, `css-modules`, `vanilla-extract`, `postcss`, `none`.
   */
  '--styling <value>'?: string

  /**
   * Sets the URL structure to support multiple markets. Must be one of: `subfolders`, `domains`, `subdomains`, `none`. Example: `--markets subfolders`.
   */
  '--markets <value>'?: string

  /**
   * Creates a global h2 shortcut for Shopify CLI using shell aliases. Deactivate with `--no-shortcut`.
   */
  '--shortcut'?: ''

  /**
   * Auto installs dependencies using the active package manager.
   */
  '--install-deps'?: ''
}
