// This is an autogenerated file. Don't edit this file manually.
export interface hydrogenbuild {
  /**
   * Show a bundle size summary after building. Defaults to true, use `--no-bundle-stats` to disable.
   *
   */
  '--bundle-stats'?: ''

  /**
   * Automatically generates GraphQL types for your project’s Storefront API queries.
   *
   */
  '--codegen'?: ''

  /**
   * Specifies a path to a codegen configuration file. Defaults to `<root>/codegen.ts` if this file exists.
   *
   */
  '--codegen-config-path <value>'?: string

  /**
   * Disables any warnings about missing standard routes.
   * @environment SHOPIFY_HYDROGEN_FLAG_DISABLE_ROUTE_WARNING
   */
  '--disable-route-warning'?: ''

  /**
   * Entry file for the worker. Defaults to `./server`.
   * @environment SHOPIFY_HYDROGEN_FLAG_ENTRY
   */
  '--entry <value>'?: string

  /**
   * Client sourcemapping is avoided by default because it makes backend code visible in the browser. Use this flag to force enabling it.
   * @environment SHOPIFY_HYDROGEN_FLAG_FORCE_CLIENT_SOURCEMAP
   */
  '--force-client-sourcemap'?: ''

  /**
   * Checks that there is exactly one valid lockfile in the project. Defaults to `true`. Deactivate with `--no-lockfile-check`.
   * @environment SHOPIFY_HYDROGEN_FLAG_LOCKFILE_CHECK
   */
  '--lockfile-check'?: ''

  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   * @environment SHOPIFY_HYDROGEN_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Controls whether server sourcemaps are generated. Default to `true`. Deactivate `--no-sourcemaps`.
   * @environment SHOPIFY_HYDROGEN_FLAG_SOURCEMAP
   */
  '--sourcemap'?: ''

  /**
   * Watches for changes and rebuilds the project writing output to disk.
   * @environment SHOPIFY_HYDROGEN_FLAG_WATCH
   */
  '--watch'?: ''
}
