// This is an autogenerated file. Don't edit this file manually.
export interface hydrogencustomeraccountpush {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   */
  '--path <value>'?: string

  /**
   * The id of the storefront the configuration should be pushed to. Must start with 'gid://shopify/HydrogenStorefront/'
   */
  '--storefront-id <value>'?: string

  /**
   * The development domain of your application.
   */
  '--dev-origin <value>': string

  /**
   * The relative url of allowed callback url for Customer Account API OAuth flow. Default is '/account/authorize'
   */
  '--relative-redirect-uri <value>'?: string

  /**
   * The relative url of allowed url that will be redirected to post-logout for Customer Account API OAuth flow. Default to nothing.
   */
  '--relative-logout-uri <value>'?: string
}
