// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `hydrogen shortcut` command:
 * @publicDocs
 */
export interface hydrogenshortcut {

}
