// This is an autogenerated file. Don't edit this file manually.
export interface hydrogenupgrade {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   */
  '--path <value>'?: string

  /**
   * A target hydrogen version to update to
   */
  '-v, --version <value>'?: string

  /**
   * Ignore warnings and force the upgrade to the target version
   */
  '-f, --force'?: ''
}
