// This is an autogenerated file. Don't edit this file manually.
/**
 * Upgrade Hydrogen project dependencies, preview features, fixes and breaking changes. The command also generates an instruction file for each upgrade.
 * @publicDocs
 */
export interface hydrogenupgrade {
  /**
   * Ignore warnings and force the upgrade to the target version
   * @environment SHOPIFY_HYDROGEN_FLAG_FORCE
   */
  '-f, --force'?: ''

  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   * @environment SHOPIFY_HYDROGEN_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * A target hydrogen version to update to
   *
   */
  '-v, --version <value>'?: string
}
