// This is an autogenerated file. Don't edit this file manually.
export interface hydrogenbuild {
  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   * @environment SHOPIFY_HYDROGEN_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Controls whether sourcemaps are generated. Default to `true`. Deactivate `--no-sourcemaps`.
   * @environment SHOPIFY_HYDROGEN_FLAG_SOURCEMAP
   */
  '--sourcemap'?: ''

  /**
   * Show a bundle size summary after building. Defaults to true, use `--no-bundle-stats` to disable.
   * 
   */
  '--bundle-stats'?: ''

  /**
   * Checks that there is exactly one valid lockfile in the project. Defaults to `true`. Deactivate with `--no-lockfile-check`.
   * @environment SHOPIFY_HYDROGEN_FLAG_LOCKFILE_CHECK
   */
  '--lockfile-check'?: ''

  /**
   * Disables any warnings about missing standard routes.
   * @environment SHOPIFY_HYDROGEN_FLAG_DISABLE_ROUTE_WARNING
   */
  '--disable-route-warning'?: ''

  /**
   * Automatically generates GraphQL types for your project’s Storefront API queries.
   * 
   */
  '--codegen'?: ''

  /**
   * Specifies a path to a codegen configuration file. Defaults to `<root>/codegen.ts` if this file exists.
   * 
   */
  '--codegen-config-path <value>'?: string
}
