// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `hydrogen env push` command:
 * @publicDocs
 */
export interface hydrogenenvpush {
  /**
   * Preview environment variable changes without pushing them.
   * @environment SHOPIFY_HYDROGEN_FLAG_DRY_RUN
   */
  '--dry-run'?: ''

  /**
   * Specifies the environment to perform the operation using its handle. Fetch the handle using the `env list` command.
   *
   */
  '--env <value>'?: string

  /**
   * Path to an environment file to override existing environment variables. Defaults to the '.env' located in your project path `--path`.
   *
   */
  '--env-file <value>'?: string

  /**
   * Push environment variable changes without confirmation.
   * @environment SHOPIFY_HYDROGEN_FLAG_FORCE
   */
  '-f, --force'?: ''

  /**
   * The path to the directory of the Hydrogen storefront. Defaults to the current directory where the command is run.
   * @environment SHOPIFY_HYDROGEN_FLAG_PATH
   */
  '--path <value>'?: string
}
