// This is an autogenerated file. Don't edit this file manually.
/**
 * Lists the Shopify organizations that you have access to, along with their organization IDs.
 * @publicDocs
 */
export interface organizationlist {
  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
