// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `search` command:
 * @publicDocs
 */
export interface search {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
