// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `store create preview` command:
 * @publicDocs
 */
export interface storecreatepreview {
  /**
   * Two-letter ISO 3166-1 alpha-2 country code for the store, such as US, CA, or GB.
   * @environment SHOPIFY_FLAG_PREVIEW_STORE_COUNTRY
   */
  '--country <value>'?: string

  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * The name of the store.
   * @environment SHOPIFY_FLAG_PREVIEW_STORE_NAME
   */
  '--name <value>'?: string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
