// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `store bulk status` command:
 * @publicDocs
 */
export interface storebulkstatus {
  /**
   * The bulk operation ID (numeric ID or full GID). If not provided, lists all bulk operations on this store in the last 7 days.
   * @environment SHOPIFY_FLAG_ID
   */
  '--id <value>'?: string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The myshopify.com domain of the store.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>': string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
