// This is an autogenerated file. Don't edit this file manually.
/**
 * Authenticates the app against the specified store for store commands and stores an online access token for later reuse.
 * 
 * Re-run this command if the stored token is missing, expires, or no longer has the scopes you need.
 * @publicDocs
 */
export interface storeauth {
  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Comma-separated Admin API scopes to request for the app.
   * @environment SHOPIFY_FLAG_SCOPES
   */
  '--scopes <value>': string

  /**
   * The myshopify.com domain of the store to authenticate against.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>': string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
