// This is an autogenerated file. Don't edit this file manually.
export interface storeauthlogout {
  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The myshopify.com domain of the store to clear local auth for.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>': string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
