// This is an autogenerated file. Don't edit this file manually.
export interface storecreate {
  /**
   * The country code for the store (e.g., US, CA, GB).
   * @environment SHOPIFY_FLAG_STORE_COUNTRY
   */
  '-c, --country <value>'?: string

  /**
   * Create a development store instead of a trial store.
   * @environment SHOPIFY_FLAG_STORE_DEV
   */
  '--dev'?: ''

  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * The name of the store.
   * @environment SHOPIFY_FLAG_STORE_NAME
   */
  '-n, --name <value>'?: string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The custom myshopify.com subdomain for the store.
   * @environment SHOPIFY_FLAG_STORE_SUBDOMAIN
   */
  '--subdomain <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
