// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `store graphiql` command:
 * @publicDocs
 */
export interface storegraphiql {
  /**
   * Allow GraphQL mutations to run against the target store.
   * @environment SHOPIFY_FLAG_ALLOW_MUTATIONS
   */
  '--allow-mutations'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Local port for the GraphiQL server. Must be between 1 and 65535.
   * @environment SHOPIFY_FLAG_PORT
   */
  '--port <value>'?: string

  /**
   * The myshopify.com domain of the store.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>': string

  /**
   * The values for any GraphQL variables in your query or mutation, in JSON format.
   * @environment SHOPIFY_FLAG_VARIABLES
   */
  '-v, --variables <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The API version to use in GraphiQL. Defaults to the latest stable version.
   * @environment SHOPIFY_FLAG_VERSION
   */
  '--version <value>'?: string
}
