// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `store auth` command:
 * @publicDocs
 */
export interface storeauth {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Comma-separated Admin API scopes to request for the app.
   * @environment SHOPIFY_FLAG_SCOPES
   */
  '--scopes <value>': string

  /**
   * The myshopify.com domain of the store to authenticate against.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>': string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
