// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `store bulk cancel` command:
 * @publicDocs
 */
export interface storebulkcancel {
  /**
   * The bulk operation ID to cancel (numeric ID or full GID).
   * @environment SHOPIFY_FLAG_ID
   */
  '--id <value>': string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The myshopify.com domain of the store.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>': string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
