// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the `store list` command:
 * @publicDocs
 */
export interface storelist {
  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The numeric organization ID. Auto-selects if you belong to a single organization.
   * @environment SHOPIFY_FLAG_ORGANIZATION_ID
   */
  '--organization-id <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
