// This is an autogenerated file. Don't edit this file manually.
export interface storeauth {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The myshopify.com domain of the store to authenticate against.
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>': string

  /**
   * Comma-separated Admin API scopes to request for the app.
   * @environment SHOPIFY_FLAG_SCOPES
   */
  '--scopes <value>': string

  /**
   * Path to a file containing the app client secret used for the OAuth code exchange.
   * @environment SHOPIFY_FLAG_CLIENT_SECRET_FILE
   */
  '--client-secret-file <value>': string

  /**
   * Local port to use for the OAuth callback server.
   * @environment SHOPIFY_FLAG_PORT
   */
  '--port <value>'?: string
}
