// This is an autogenerated file. Don't edit this file manually.
export interface themepush {
  /**
   * Allow push to a live theme.
   * @environment SHOPIFY_FLAG_ALLOW_LIVE
   */
  '-a, --allow-live'?: ''

  /**
   * Push theme files from your remote development theme.
   * @environment SHOPIFY_FLAG_DEVELOPMENT
   */
  '-d, --development'?: ''

  /**
   * The environment to apply to the current command.
   * @environment SHOPIFY_FLAG_ENVIRONMENT
   */
  '-e, --environment <value>'?: string

  /**
   * Skip downloading the specified files (Multiple flags allowed).
   * @environment SHOPIFY_FLAG_IGNORE
   */
  '-x, --ignore <value>'?: string

  /**
   * Output JSON instead of a UI.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Push theme files from your remote live theme.
   * @environment SHOPIFY_FLAG_LIVE
   */
  '-l, --live'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Prevent deleting remote files that don't exist locally.
   * @environment SHOPIFY_FLAG_NODELETE
   */
  '-n, --nodelete'?: ''

  /**
   * Download only the specified files (Multiple flags allowed).
   * @environment SHOPIFY_FLAG_ONLY
   */
  '-o, --only <value>'?: string

  /**
   * Password generated from the Theme Access app.
   * @environment SHOPIFY_CLI_THEME_TOKEN
   */
  '--password <value>'?: string

  /**
   * The path to your theme directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Publish as the live theme after uploading.
   * @environment SHOPIFY_FLAG_PUBLISH
   */
  '-p, --publish'?: ''

  /**
   * Store URL. It can be the store prefix (example) or the full myshopify.com URL (example.myshopify.com, https://example.myshopify.com).
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * Theme ID or name of the remote theme.
   * @environment SHOPIFY_FLAG_THEME_ID
   */
  '-t, --theme <value>'?: string

  /**
   * Create a new unpublished theme and push to it.
   * @environment SHOPIFY_FLAG_UNPUBLISHED
   */
  '-u, --unpublished'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
