// This is an autogenerated file. Don't edit this file manually.
export interface themeinfo {
  /**
   * Retrieve info from your development theme.
   */
  '-d, --development'?: ''

  /**
   * The environment to apply to the current command.
   */
  '-e, --environment <value>'?: string

  /**
   * Output the theme info as JSON.
   */
  '--json'?: ''

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * Password generated from the Theme Access app.
   */
  '--password <value>'?: string

  /**
   * Store URL. It can be the store prefix (johns-apparel) or the full myshopify.com URL (johns-apparel.myshopify.com, https://johns-apparel.myshopify.com).
   */
  '-s, --store <value>'?: string

  /**
   * Theme ID or name of the remote theme.
   */
  '-t, --theme <value>'?: string

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''
}
