// This is an autogenerated file. Don't edit this file manually.
/**
 * Starts the [Language Server](/docs/themes/tools/cli/language-server).
 * @publicDocs
 */
export interface themelanguageserver {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
