// This is an autogenerated file. Don't edit this file manually.
export interface themegeneratetemplate {
  /**
   * Name of the template
   * @environment SHOPIFY_FLAG_TEMPLATE_NAME
   */
  '-n, --name <value>'?: string

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path to your theme directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Type of template to generate
   * @environment SHOPIFY_FLAG_TEMPLATE_TYPE
   */
  '-t, --type <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
