// This is an autogenerated file. Don't edit this file manually.
export interface themeinit {
  /**
   * The Git URL to clone from. Defaults to Shopify's example theme, Dawn: https://github.com/Shopify/dawn.git
   */
  '-u, --clone-url <value>'?: string

  /**
   * Downloads the latest release of the `clone-url`
   */
  '-l, --latest'?: ''

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * The path to your theme directory.
   */
  '--path <value>'?: string

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''
}
