// This is an autogenerated file. Don't edit this file manually.
/**
 * Returns links that let you preview the specified theme. The following links are returned:
 * 
 *   - A link to the [editor](/docs/themes/tools/online-editor) for the theme in the Shopify admin.
 *   - A [preview link](https://help.shopify.com/manual/online-store/themes/adding-themes#share-a-theme-preview-with-others) that you can share with other developers.
 * 
 *   If you don't specify a theme, then you're prompted to select the theme to open from the list of the themes in your store.
 * @publicDocs
 */
export interface themeopen {
  /**
   * Open your development theme.
   * @environment SHOPIFY_FLAG_DEVELOPMENT
   */
  '-d, --development'?: ''

  /**
   * Open the theme editor for the specified theme in the browser.
   * @environment SHOPIFY_FLAG_EDITOR
   */
  '-E, --editor'?: ''

  /**
   * The environment to apply to the current command.
   * @environment SHOPIFY_FLAG_ENVIRONMENT
   */
  '-e, --environment <value>'?: string

  /**
   * Open your live (published) theme.
   * @environment SHOPIFY_FLAG_LIVE
   */
  '-l, --live'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Password generated from the Theme Access app or an Admin API token.
   * @environment SHOPIFY_CLI_THEME_TOKEN
   */
  '--password <value>'?: string

  /**
   * The path where you want to run the command. Defaults to the current working directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Store URL. It can be the store prefix (example) or the full myshopify.com URL (example.myshopify.com, https://example.myshopify.com).
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * Theme ID or name of the remote theme.
   * @environment SHOPIFY_FLAG_THEME_ID
   */
  '-t, --theme <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
