// This is an autogenerated file. Don't edit this file manually.
export interface themepreview {
  /**
   * The environment to apply to the current command.
   * @environment SHOPIFY_FLAG_ENVIRONMENT
   */
  '-e, --environment <value>'?: string

  /**
   * Output the preview URL and identifier as JSON.
   * @environment SHOPIFY_FLAG_JSON
   */
  '--json'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Automatically launch the theme preview in your default web browser.
   * @environment SHOPIFY_FLAG_OPEN
   */
  '--open'?: ''

  /**
   * Path to a JSON overrides file.
   * @environment SHOPIFY_FLAG_OVERRIDES
   */
  '--overrides <value>': string

  /**
   * Password generated from the Theme Access app or an Admin API token.
   * @environment SHOPIFY_CLI_THEME_TOKEN
   */
  '--password <value>'?: string

  /**
   * The path where you want to run the command. Defaults to the current working directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * An existing preview identifier to update instead of creating a new preview.
   * @environment SHOPIFY_FLAG_PREVIEW_ID
   */
  '--preview-id <value>'?: string

  /**
   * Store URL. It can be the store prefix (example) or the full myshopify.com URL (example.myshopify.com, https://example.myshopify.com).
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * Theme ID or name of the remote theme.
   * @environment SHOPIFY_FLAG_THEME_ID
   */
  '-t, --theme <value>': string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
