// This is an autogenerated file. Don't edit this file manually.
/**
 * Packages your local theme files into a ZIP file that can be uploaded to Shopify.
 * 
 *   Only folders that match the [default Shopify theme folder structure](/docs/storefronts/themes/tools/cli#directory-structure) are included in the package.
 * 
 *   The package includes the `listings` directory if present (required for multi-preset themes per [Theme Store requirements](/docs/storefronts/themes/store/requirements#adding-presets-to-your-theme-zip-submission)).
 * 
 *   The ZIP file uses the name `theme_name-theme_version.zip`, based on parameters in your [settings_schema.json](/docs/storefronts/themes/architecture/config/settings-schema-json) file.
 * @publicDocs
 */
export interface themepackage {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path where you want to run the command. Defaults to the current working directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
