// This is an autogenerated file. Don't edit this file manually.
export interface themecheck {
  /**
   * Automatically fix offenses
   */
  '-a, --auto-correct'?: ''

  /**
   * Use the config provided, overriding .theme-check.yml if present
      Supports all theme-check: config values, e.g., theme-check:theme-app-extension,
      theme-check:recommended, theme-check:all
      For backwards compatibility, :theme_app_extension is also supported 
   */
  '-C, --config <value>'?: string

  /**
   * The environment to apply to the current command.
   */
  '-e, --environment <value>'?: string

  /**
   * Minimum severity for exit with error code
   */
  '--fail-level <value>'?: string

  /**
   * Generate a .theme-check.yml file
   */
  '--init'?: ''

  /**
   * List enabled checks
   */
  '--list'?: ''

  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * The output format to use
   */
  '-o, --output <value>'?: string

  /**
   * The path to your theme directory.
   */
  '--path <value>'?: string

  /**
   * Output active config to STDOUT
   */
  '--print'?: ''

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''

  /**
   * Print Theme Check version
   */
  '-v, --version'?: ''
}
