// This is an autogenerated file. Don't edit this file manually.
/**
 * Clones a Git repository to your local machine to use as the starting point for building a theme.
 * 
 *   If no Git repository is specified, then this command creates a copy of Shopify's [Skeleton theme](https://github.com/Shopify/skeleton-theme.git), with the specified name in the current folder. If no name is provided, then you're prompted to enter one.
 * 
 *   > Caution: If you're building a theme for the Shopify Theme Store, then you can use our example theme as a starting point. However, the theme that you submit needs to be [substantively different from existing themes](/docs/themes/store/requirements#uniqueness) so that it provides added value for users.
 *   
 * @publicDocs
 */
export interface themeinit {
  /**
   * The Git URL to clone from. Defaults to Shopify's Skeleton theme.
   * @environment SHOPIFY_FLAG_CLONE_URL
   */
  '-u, --clone-url <value>'?: string

  /**
   * Downloads the latest release of the `clone-url`
   * @environment SHOPIFY_FLAG_LATEST
   */
  '-l, --latest'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * The path where you want to run the command. Defaults to the current working directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
