// This is an autogenerated file. Don't edit this file manually.
export interface themepush {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The path where you want to run the command. Defaults to the current working directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Password generated from the Theme Access app or an Admin API token.
   * @environment SHOPIFY_CLI_THEME_TOKEN
   */
  '--password <value>'?: string

  /**
   * Store URL. It can be the store prefix (example) or the full myshopify.com URL (example.myshopify.com, https://example.myshopify.com).
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * The environment to apply to the current command.
   * @environment SHOPIFY_FLAG_ENVIRONMENT
   */
  '-e, --environment <value>'?: string

  /**
   * Upload only the specified files (Multiple flags allowed). Wrap the value in double quotes if you're using wildcards.
   * @environment SHOPIFY_FLAG_ONLY
   */
  '-o, --only <value>'?: string

  /**
   * Skip uploading the specified files (Multiple flags allowed). Wrap the value in double quotes if you're using wildcards.
   * @environment SHOPIFY_FLAG_IGNORE
   */
  '-x, --ignore <value>'?: string

  /**
   * Output the result as JSON. Automatically disables color output.
   * @environment SHOPIFY_FLAG_JSON
   */
  '-j, --json'?: ''

  /**
   * Theme ID or name of the remote theme.
   * @environment SHOPIFY_FLAG_THEME_ID
   */
  '-t, --theme <value>'?: string

  /**
   * Push theme files from your remote development theme.
   * @environment SHOPIFY_FLAG_DEVELOPMENT
   */
  '-d, --development'?: ''

  /**
   * Unique identifier for a development theme context (e.g., PR number, branch name). Reuses an existing development theme with this context name, or creates one if none exists.
   * @environment SHOPIFY_FLAG_DEVELOPMENT_CONTEXT
   */
  '-c, --development-context <value>'?: string

  /**
   * Push theme files from your remote live theme.
   * @environment SHOPIFY_FLAG_LIVE
   */
  '-l, --live'?: ''

  /**
   * Create a new unpublished theme and push to it.
   * @environment SHOPIFY_FLAG_UNPUBLISHED
   */
  '-u, --unpublished'?: ''

  /**
   * Prevent deleting remote files that don't exist locally.
   * @environment SHOPIFY_FLAG_NODELETE
   */
  '-n, --nodelete'?: ''

  /**
   * Allow push to a live theme.
   * @environment SHOPIFY_FLAG_ALLOW_LIVE
   */
  '-a, --allow-live'?: ''

  /**
   * Publish as the live theme after uploading.
   * @environment SHOPIFY_FLAG_PUBLISH
   */
  '-p, --publish'?: ''

  /**
   * Require theme check to pass without errors before pushing. Warnings are allowed.
   * @environment SHOPIFY_FLAG_STRICT_PUSH
   */
  '--strict'?: ''

  /**
   * The listing preset to use for multi-preset themes. Applies preset files from listings/[preset-name] directory.
   * @environment SHOPIFY_FLAG_LISTING
   */
  '--listing <value>'?: string
}
