// This is an autogenerated file. Don't edit this file manually.
export interface themerename {
  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''

  /**
   * The path where you want to run the command. Defaults to the current working directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Password generated from the Theme Access app or an Admin API token.
   * @environment SHOPIFY_CLI_THEME_TOKEN
   */
  '--password <value>'?: string

  /**
   * Store URL. It can be the store prefix (example) or the full myshopify.com URL (example.myshopify.com, https://example.myshopify.com).
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * The environment to apply to the current command.
   * @environment SHOPIFY_FLAG_ENVIRONMENT
   */
  '-e, --environment <value>'?: string

  /**
   * The new name for the theme.
   * @environment SHOPIFY_FLAG_NEW_NAME
   */
  '-n, --name <value>'?: string

  /**
   * Rename your development theme.
   * @environment SHOPIFY_FLAG_DEVELOPMENT
   */
  '-d, --development'?: ''

  /**
   * Theme ID or name of the remote theme.
   * @environment SHOPIFY_FLAG_THEME_ID
   */
  '-t, --theme <value>'?: string

  /**
   * Rename your remote live theme.
   * @environment SHOPIFY_FLAG_LIVE
   */
  '-l, --live'?: ''
}
