// This is an autogenerated file. Don't edit this file manually.
export interface themepull {
  /**
   * Pull theme files from your remote development theme.
   * @environment SHOPIFY_FLAG_DEVELOPMENT
   */
  '-d, --development'?: ''

  /**
   * The environment to apply to the current command.
   * @environment SHOPIFY_FLAG_ENVIRONMENT
   */
  '-e, --environment <value>'?: string

  /**
   * Skip downloading the specified files (Multiple flags allowed). Wrap the value in double quotes if you're using wildcards.
   * @environment SHOPIFY_FLAG_IGNORE
   */
  '-x, --ignore <value>'?: string

  /**
   * Pull theme files from your remote live theme.
   * @environment SHOPIFY_FLAG_LIVE
   */
  '-l, --live'?: ''

  /**
   * Disable color output.
   * @environment SHOPIFY_FLAG_NO_COLOR
   */
  '--no-color'?: ''

  /**
   * Prevent deleting local files that don't exist remotely.
   * @environment SHOPIFY_FLAG_NODELETE
   */
  '-n, --nodelete'?: ''

  /**
   * Download only the specified files (Multiple flags allowed). Wrap the value in double quotes if you're using wildcards.
   * @environment SHOPIFY_FLAG_ONLY
   */
  '-o, --only <value>'?: string

  /**
   * Password generated from the Theme Access app or an Admin API token.
   * @environment SHOPIFY_CLI_THEME_TOKEN
   */
  '--password <value>'?: string

  /**
   * The path where you want to run the command. Defaults to the current working directory.
   * @environment SHOPIFY_FLAG_PATH
   */
  '--path <value>'?: string

  /**
   * Store URL. It can be the store prefix (example) or the full myshopify.com URL (example.myshopify.com, https://example.myshopify.com).
   * @environment SHOPIFY_FLAG_STORE
   */
  '-s, --store <value>'?: string

  /**
   * Theme ID or name of the remote theme.
   * @environment SHOPIFY_FLAG_THEME_ID
   */
  '-t, --theme <value>'?: string

  /**
   * Increase the verbosity of the output.
   * @environment SHOPIFY_FLAG_VERBOSE
   */
  '--verbose'?: ''
}
