// This is an autogenerated file. Don't edit this file manually.
export interface adminlink {
  /** Text to be displayed on the surface */
  'name': string

  /** Description of the link */
  'description'?: string

  'targeting': object[]

  /** URL or app path to be navigated to when the link is clicked */
  'targeting[].url': string

  /** Target in the surface where the link will be rendered */
  'targeting[].target': 'admin.abandoned-checkout-details.action.link' | 'admin.discount-index.action.link' | 'admin.discount-index.selection-action.link' | 'admin.discount-details.action.link' | 'admin.customer-index.action.link' | 'admin.customer-index.selection-action.link' | 'admin.customer-details.action.link' | 'admin.order-index.action.link' | 'admin.order-index.selection-action.link' | 'admin.order-details.action.link' | 'admin.draft-order-details.action.link' | 'admin.draft-order-index.action.link' | 'admin.draft-order-index.selection-action.link' | 'admin.product-index.action.link' | 'admin.product-index.selection-action.link' | 'admin.product-details.action.link' | 'admin.product-variant-details.action.link' | 'admin.product-variant-index.selection-action.link' | 'admin.collection-details.action.link' | 'admin.collection-index.action.link' | 'admin.order-fulfilled-card.action.link' | 'admin.app.support.link' | 'admin.page-index.action.link' | 'admin.page-details.action.link' | 'admin.blog-details.action.link' | 'admin.article-details.action.link' | 'admin.app.intent.link'

  /** App intents configuration for admin.app.intent.render target */
  'targeting[].intents'?: object[]

  /** The intent action identifier */
  'targeting[].intents[].action': string

  /** The intent type */
  'targeting[].intents[].type': string

  /** Module reference for the schema */
  'targeting[].intents[].schema': string

  /** Tools JSON schema */
  'targeting[].tools'?: string

  /** Instructions markdown file */
  'targeting[].instructions'?: string

  /** Schema files for intents */
  'targeting[].build_manifest.assets.intents'?: object[]

  /** Path to the schema file to upload */
  'targeting[].build_manifest.assets.intents[].filepath': string

  /** Module reference for the schema */
  'targeting[].build_manifest.assets.intents[].module': string

  /** Whether the asset is static */
  'targeting[].build_manifest.assets.intents[].static'?: boolean

  /** Path to the schema file to upload */
  'targeting[].build_manifest.assets.tools.filepath': string

  /** Module reference for the schema */
  'targeting[].build_manifest.assets.tools.module': string

  /** Whether the asset is static */
  'targeting[].build_manifest.assets.tools.static'?: boolean

  /** Path to the schema file to upload */
  'targeting[].build_manifest.assets.instructions.filepath': string

  /** Module reference for the schema */
  'targeting[].build_manifest.assets.instructions.module': string

  /** Whether the asset is static */
  'targeting[].build_manifest.assets.instructions.static'?: boolean

  /** Localization of the link text */
  'localization'?: object

  /** Uploaded files for the module */
  'uploaded_files'?: object
}
