// This is an autogenerated file. Don't edit this file manually.
export interface checkoutuiextension {
  'name': string

  'type'?: string

  'handle'?: string

  'uid'?: string

  'description'?: string

  'api_version'?: string

  'extension_points'?: string[]

  'capabilities.network_access'?: boolean

  'capabilities.block_progress'?: boolean

  'capabilities.api_access'?: boolean

  'capabilities.collect_buyer_consent.sms_marketing'?: boolean

  'capabilities.collect_buyer_consent.customer_privacy'?: boolean

  'capabilities.iframe.sources'?: string[]

  'supported_features.runs_offline'?: boolean

  'settings.fields'?: unknown

  'metafields'?: object[]

  'metafields[].namespace': string

  'metafields[].key': string
}
