// This is an autogenerated file. Don't edit this file manually.
export interface editorextensioncollection {
  'name': string

  'type': string

  'handle'?: string

  'uid'?: string

  'description'?: string

  'api_version'?: string

  'extension_points'?: unknown

  'capabilities.network_access'?: boolean

  'capabilities.block_progress'?: boolean

  'capabilities.api_access'?: boolean

  'capabilities.collect_buyer_consent.sms_marketing'?: boolean

  'capabilities.collect_buyer_consent.customer_privacy'?: boolean

  'capabilities.iframe.sources'?: string[]

  'supported_features.runs_offline'?: boolean

  'settings.fields'?: object[]

  'settings.fields[].key'?: string

  'settings.fields[].name'?: string

  'settings.fields[].description'?: string

  'settings.fields[].required'?: boolean

  'settings.fields[].default_value'?: unknown

  'settings.fields[].type': string

  'settings.fields[].validations'?: unknown

  'settings.fields[].marketingActivityCreateUrl'?: string

  'settings.fields[].marketingActivityDeleteUrl'?: string

  'include'?: object[]

  'include[].handle': string

  'includes'?: string[]
}
