// This is an autogenerated file. Don't edit this file manually.
export interface global {
  'client_id': string

  'build.automatically_update_urls_on_dev'?: boolean

  'build.dev_store_url'?: string

  'build.include_config_on_deploy'?: boolean

  'extension_directories'?: string[]

  'web_directories'?: string[]

  /** The name of your app. */
  'name': string

  /** The URL handle of your app. */
  'handle'?: string
}
