// This is an autogenerated file. Don't edit this file manually.
export interface marketingactivity {
  'name'?: string

  'title': string

  'description': string

  'api_path': string

  'tactic': 'ad' | 'retargeting' | 'post' | 'message' | 'transactional' | 'newsletter' | 'abandoned_cart' | 'affililate' | 'loyalty' | 'link' | 'storefront_app'

  'marketing_channel': 'social' | 'search' | 'email' | 'sms' | 'display' | 'marketplace'

  'referring_domain'?: string

  'is_automation'?: boolean

  'use_external_editor'?: boolean

  'preview_data.types': object[]

  'preview_data.types[].label': string

  'preview_data.types[].value': string

  'fields': object[]
}
