// This is an autogenerated file. Don't edit this file manually.
export interface uiextension {
  'name': string

  'type': string

  'handle'?: string

  'uid'?: string

  'description'?: string

  'api_version'?: string

  'extension_points'?: object[]

  'extension_points[].target': string

  'extension_points[].module': string

  'extension_points[].should_render.module': string

  'extension_points[].tools'?: string

  'extension_points[].instructions'?: string

  'extension_points[].metafields'?: object[]

  'extension_points[].metafields[].namespace': string

  'extension_points[].metafields[].key': string

  'extension_points[].default_placement'?: string

  'extension_points[].urls.edit'?: string

  'extension_points[].capabilities.allow_direct_linking'?: boolean

  'extension_points[].preloads.chat'?: string

  'capabilities.network_access'?: boolean

  'capabilities.block_progress'?: boolean

  'capabilities.api_access'?: boolean

  'capabilities.collect_buyer_consent.sms_marketing'?: boolean

  'capabilities.collect_buyer_consent.customer_privacy'?: boolean

  'capabilities.iframe.sources'?: string[]

  'supported_features.runs_offline'?: boolean

  'settings.fields'?: object[]

  'settings.fields[].key'?: string

  'settings.fields[].name'?: string

  'settings.fields[].description'?: string

  'settings.fields[].required'?: boolean

  'settings.fields[].default_value'?: unknown

  'settings.fields[].type': string

  'settings.fields[].validations'?: unknown

  'settings.fields[].marketingActivityCreateUrl'?: string

  'settings.fields[].marketingActivityDeleteUrl'?: string

  'targeting'?: object[]

  'targeting[].target': string

  'targeting[].module': string

  'targeting[].should_render.module': string

  'targeting[].tools'?: string

  'targeting[].instructions'?: string

  'targeting[].metafields'?: object[]

  'targeting[].metafields[].namespace': string

  'targeting[].metafields[].key': string

  'targeting[].default_placement'?: string

  'targeting[].urls.edit'?: string

  'targeting[].capabilities.allow_direct_linking'?: boolean

  'targeting[].preloads.chat'?: string

  'metafields'?: object[]

  'metafields[].namespace': string

  'metafields[].key': string
}
