// This is an autogenerated file. Don't edit this file manually.
export interface webhooks {
  'webhooks.api_version': string

  'webhooks.privacy_compliance.customer_deletion_url'?: string

  'webhooks.privacy_compliance.customer_data_request_url'?: string

  'webhooks.privacy_compliance.shop_deletion_url'?: string

  'webhooks.subscriptions'?: object[]

  'webhooks.subscriptions[].topics'?: string[]

  'webhooks.subscriptions[].actions'?: string[]

  'webhooks.subscriptions[].uri': string

  'webhooks.subscriptions[].include_fields'?: string[]

  'webhooks.subscriptions[].filter'?: string

  'webhooks.subscriptions[].payload_query'?: string

  'webhooks.subscriptions[].name'?: string

  'webhooks.subscriptions[].compliance_topics'?: string[]
}
