#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

pushd $SCRIPT_DIR/.. > /dev/null
yarn nx build cli app
popd > /dev/null

$SCRIPT_DIR/../packages/cli/bin/dev.js $@
