import type {Severity, Capabilities} from '../types.js'

export interface RuleCatalogEntry {
  id: string
  title: string
  severity: Severity
  points: number
  description: string
  fix: string
  guide?: string
  requires?: keyof Capabilities
  status?: 'active' | 'planned'
}

export const RULE_CATALOG: RuleCatalogEntry[] = [
  {
    id: 'DEPRECATED_SCRIPT_TAG_SCOPE',
    title: 'Using deprecated write_script_tags scope',
    severity: 'critical',
    points: -30,
    description: 'Detects the deprecated write_script_tags OAuth scope in shopify.app.toml.',
    fix: 'Remove write_script_tags from scopes and migrate to app embeds.',
    guide: 'https://shopify.dev/docs/apps/online-store/app-embeds',
  },
  {
    id: 'SCOPE_OVER_REQUEST',
    title: 'OAuth scope may be over-requested',
    severity: 'high',
    points: -12,
    description: "Detects declared OAuth scopes that don't appear to be used by the app code.",
    fix: 'Remove unused scopes or add the code path that needs them.',
    guide: 'https://shopify.dev/docs/api/usage/access-scopes',
  },
  {
    id: 'MISSING_SRI',
    title: 'Missing subresource integrity on external script',
    severity: 'high',
    points: -15,
    description: "Detects external script tags in Liquid or HTML that don't declare integrity metadata.",
    fix: 'Add integrity and crossorigin attributes to the script tag.',
    guide: 'https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity',
    requires: 'theme_app_extension',
  },
  {
    id: 'UNSAFE_INNERHTML',
    title: 'Unsafe HTML assignment',
    severity: 'critical',
    points: -25,
    description: 'Detects innerHTML, outerHTML, and insertAdjacentHTML receiving non-literal values.',
    fix: 'Use textContent where possible or sanitize with DOMPurify before rendering.',
    guide: 'https://shopify.dev/docs/apps/online-store/security#xss-prevention',
    requires: 'theme_app_extension',
  },
  {
    id: 'LIQUID_UNSAFE_RENDER',
    title: 'Unsafe Liquid rendering with | raw filter',
    severity: 'critical',
    points: -25,
    description: 'Detects Liquid output that renders unescaped values through the raw filter.',
    fix: 'Replace | raw with | escape unless the value is proven trusted HTML.',
    guide: 'https://shopify.dev/docs/api/liquid/filters/raw',
    requires: 'theme_app_extension',
  },
  {
    id: 'EXTERNAL_CDN_DEPENDENCY',
    title: 'External CDN dependency',
    severity: 'medium',
    points: -7,
    description: 'Detects extension code loading dependencies or fetches from external non-Shopify domains.',
    fix: 'Bundle the dependency locally or self-host it behind a trusted boundary.',
    requires: 'theme_app_extension',
  },
  {
    id: 'INSECURE_WEBHOOK_URL',
    title: 'Webhook URL is not HTTPS',
    severity: 'high',
    points: -12,
    description: 'Detects webhook subscriptions configured with non-HTTPS absolute URLs.',
    fix: 'Change the webhook URI to use HTTPS.',
    guide: 'https://shopify.dev/docs/apps/webhooks',
    requires: 'webhooks',
  },
  {
    id: 'COMMITTED_SECRET',
    title: 'Committed secret or environment file',
    severity: 'critical',
    points: -50,
    description: 'Detects environment files and common API key/token patterns in source files.',
    fix: 'Remove committed secrets, rotate exposed values, and store them in environment variables.',
  },
  {
    id: 'OUTDATED_SHOPIFY_SDK',
    title: 'Outdated Shopify SDK',
    severity: 'medium',
    points: -5,
    description: 'Detects Shopify SDK packages below the expected current major version.',
    fix: 'Upgrade the Shopify SDK dependency to the current supported major.',
    guide: 'https://shopify.dev/docs/apps/tools/sdk',
  },
  {
    id: 'KNOWN_CVE_IN_DEPENDENCY',
    title: 'Known CVE in dependency',
    severity: 'high',
    points: -8,
    description: 'Detects a small curated set of dependency versions with known CVEs.',
    fix: 'Upgrade the dependency to a patched version.',
  },
  {
    id: 'MISSING_IP_ALLOWLIST',
    title: 'No IP address spaces declared in app config',
    severity: 'high',
    points: -10,
    description: 'Detects apps with no IP allowlist declaration or an allowlist open to every address.',
    fix: 'Declare only the server IP ranges that should access Shopify APIs.',
    guide: 'https://shopify.dev/docs/apps/launch/security-review#ip-allowlisting',
    status: 'planned',
  },
  {
    id: 'EXPIRING_OFFLINE_TOKEN',
    title: 'Expiring offline access tokens not enabled',
    severity: 'high',
    points: -20,
    description: 'Detects apps that have not opted into expiring offline access tokens (Jan 1, 2026 deadline).',
    fix: 'Enable future.expiringOfflineAccessTokens: true (Remix) or add user session repository (Rails).',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/access-token-types/online-access-tokens',
  },
  {
    id: 'METAFIELD_OFFLINE_TOKEN',
    title: 'Metafield write using offline token context',
    severity: 'high',
    points: -15,
    description:
      'Detects metafield writes (metafieldsSet) in offline-token contexts. Online tokens provide user attribution and expiry.',
    fix: 'Use authenticate.admin(request) instead of unauthenticated.admin() for metafield writes.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/access-token-types/online-access-tokens',
  },
  {
    id: 'MISSING_EMBEDDED_CSP',
    title: 'Embedded app missing frame-ancestors CSP directive',
    severity: 'high',
    points: -10,
    description: 'Detects embedded apps that set document response headers but omit frame-ancestors.',
    fix: 'Add frame-ancestors to CSP, restricted to the authenticated shop domain and admin.shopify.com.',
    guide: 'https://shopify.dev/docs/apps/build/security/set-up-iframe-protection',
  },
  {
    id: 'MISSING_COMPLIANCE_WEBHOOKS',
    title: 'Missing mandatory GDPR compliance webhooks',
    severity: 'high',
    points: -15,
    description:
      'Detects apps missing mandatory compliance webhooks (shop/redact, customers/data_request, customers/redact).',
    fix: 'Add the missing webhook subscriptions to shopify.app.toml.',
    guide: 'https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks',
  },
  {
    id: 'EOL_API_VERSION',
    title: 'End-of-life API version',
    severity: 'medium',
    points: -10,
    description: 'Detects apps pinned to API versions older than ~24 months from the latest release.',
    fix: 'Update api_version in shopify.app.toml and the ApiVersion enum in shopify.server.ts.',
    guide: 'https://shopify.dev/docs/api/usage/versioning',
  },
  {
    id: 'WEAK_SHOP_VALIDATION',
    title: 'Shop domain validation regex is not anchored',
    severity: 'high',
    points: -15,
    description: 'Detects unanchored myshopify.com regexes that allow domain spoofing and token theft.',
    fix: 'Anchor the regex with ^ and $ to prevent prefix/suffix attacks.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/get-access-tokens/oauth',
  },
  {
    id: 'APP_PROXY_LIQUID_INJECTION',
    title: 'App proxy Liquid injection risk',
    severity: 'critical',
    points: -25,
    description: 'Detects app proxy endpoints that interpolate request parameters into application/liquid responses.',
    fix: "Don't interpolate user input into application/liquid responses. Use application/json or escape all input.",
    guide: 'https://shopify.dev/docs/apps/online-store/app-proxies',
  },
  {
    id: 'MISSING_TENANT_ISOLATION',
    title: 'Database query may not be scoped by shop',
    severity: 'high',
    points: -20,
    description: "Detects database queries in authenticated routes that don't reference the shop domain or session.",
    fix: "Add the authenticated shop to the query's where clause.",
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/session-tokens',
  },
  {
    id: 'TOKEN_LEAKAGE',
    title: 'Token or secret may be logged',
    severity: 'high',
    points: -20,
    description: 'Detects log statements that reference access tokens, session tokens, or API secrets.',
    fix: 'Remove the token from the log statement or redact it.',
  },
  {
    id: 'OPEN_REDIRECT',
    title: 'Open redirect in auth callback',
    severity: 'medium',
    points: -12,
    description: 'Detects redirect targets taken from request parameters without validation.',
    fix: 'Validate the redirect URL against an allowlist of permitted domains.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization',
  },
  {
    id: 'UNAUTHENTICATED_ENDPOINT',
    title: 'Route handler lacks recognized auth verification',
    severity: 'high',
    points: -15,
    description:
      'Detects backend routes with no recognized auth guard or catch-block fallback to request-controlled shop input.',
    fix: 'Require Shopify session validation before accessing shop data.',
    guide: 'https://shopify.dev/docs/apps/auth',
    requires: 'has_backend',
  },
  {
    id: 'REQUEST_CONTROLLED_ADMIN_CONTEXT',
    title: 'Request input selects Admin API shop context',
    severity: 'critical',
    points: -30,
    description:
      "Detects request-derived shop values passed into unauthenticated.admin(...), allowing callers to select another shop's Admin API context.",
    fix: 'Use the Admin API context returned by authenticate.admin(request). Never pass form, JSON, query, or route input into unauthenticated.admin(...).',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/online-access-tokens',
  },
  {
    id: 'RUNTIME_CONFIG_SCRIPT_EXECUTION',
    title: 'Runtime config field is executed as script',
    severity: 'critical',
    points: -25,
    description: 'Detects config fields named as executable script used in files that inject or evaluate scripts.',
    fix: 'Ship storefront JavaScript as static versioned extension assets and treat runtime config as data only.',
  },
  {
    id: 'DEPRECATED_SCRIPT_TAG_API',
    title: 'Deprecated ScriptTag API expands storefront attack surface',
    severity: 'high',
    points: -12,
    description: 'Detects ScriptTag creation or update calls in app code.',
    fix: 'Migrate storefront UI to a theme app extension or analytics to a web pixel.',
    guide: 'https://shopify.dev/docs/apps/build/online-store/theme-app-extensions',
  },
  {
    id: 'APP_PROXY_UNVERIFIED_SIGNATURE',
    title: 'App proxy request trusted without signature verification',
    severity: 'high',
    points: -15,
    description: 'Detects app proxy parameters read without visible signature verification.',
    fix: 'Verify app proxy signatures before trusting shop, customer, or path parameters.',
    guide: 'https://shopify.dev/docs/apps/build/online-store/app-proxies/authenticate-app-proxies',
    requires: 'app_proxy',
  },
  {
    id: 'REQUEST_DERIVED_SHOP_SCOPE',
    title: 'Query scoped by shop value taken from request input',
    severity: 'high',
    points: -15,
    description:
      'Detects queries whose shop scope comes from request params rather than the authenticated session. Presence of a shop key is not proof of scoping when its value is attacker-controlled.',
    fix: 'Scope the query with the shop from the authenticated session, or verify the supplied shop against a signed session or HMAC first.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/session-tokens',
  },
  {
    id: 'UNSCOPED_SHOP_CONFIG_WRITE',
    title: 'Config write trusts shop from request input',
    severity: 'high',
    points: -15,
    description:
      'Detects settings or metafield writes scoped by request-controlled shop input without visible auth verification.',
    fix: 'Derive the target shop from an authenticated session or verified HMAC.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/session-tokens',
  },
  {
    id: 'STATIC_FRAME_ANCESTORS',
    title: 'Embedded app frame-ancestors uses a wildcard',
    severity: 'high',
    points: -12,
    description: 'Detects wildcard frame-ancestors CSP policies in Shopify app code.',
    fix: 'Build frame-ancestors per request from the authenticated shop domain and admin.shopify.com.',
    guide: 'https://shopify.dev/docs/apps/build/security/set-up-iframe-protection',
  },
]

export const findRule = (ruleId: string): RuleCatalogEntry | undefined =>
  RULE_CATALOG.find((rule) => rule.id.toLowerCase() === ruleId.toLowerCase())
