import type {Severity, Capabilities} from '../types.js'

export interface RuleCatalogEntry {
  id: string
  title: string
  severity: Severity
  points: number
  description: string
  fix: string
  guide?: string
  requires?: keyof Capabilities
  status?: 'active' | 'planned' | 'investigate'
}

export const RULE_CATALOG: RuleCatalogEntry[] = [
  {
    id: 'DEPRECATED_SCRIPT_TAG_SCOPE',
    title: 'Deprecated ScriptTag capability',
    severity: 'medium',
    points: -10,
    description: 'Detects the deprecated write_script_tags OAuth scope in shopify.app.toml.',
    fix: 'Remove write_script_tags from scopes and migrate to app embeds.',
    guide: 'https://shopify.dev/docs/apps/online-store/app-embeds',
  },
  {
    id: 'SCOPE_OVER_REQUEST',
    title: 'OAuth scope may be over-requested',
    severity: 'high',
    points: -12,
    description: "Detects declared OAuth scopes that don't appear to be used by the app code.",
    fix: 'Remove unused scopes or add the code path that needs them.',
    guide: 'https://shopify.dev/docs/api/usage/access-scopes',
  },
  {
    id: 'MISSING_SRI',
    status: 'investigate',
    title: 'Missing subresource integrity on external script',
    severity: 'high',
    points: 0,
    description: "Investigates external script tags in Liquid or HTML that don't declare integrity metadata.",
    fix: 'Add integrity and crossorigin attributes to the script tag.',
    guide: 'https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity',
    requires: 'theme_app_extension',
  },
  {
    id: 'UNSAFE_INNERHTML',
    title: 'Unsafe HTML assignment',
    severity: 'high',
    points: -25,
    description: 'Detects innerHTML, outerHTML, and insertAdjacentHTML receiving non-literal values.',
    fix: 'Use textContent where possible or sanitize with DOMPurify before rendering.',
    guide: 'https://shopify.dev/docs/apps/online-store/security#xss-prevention',
    requires: 'theme_app_extension',
  },
  {
    id: 'LIQUID_UNSAFE_RENDER',
    title: 'Unsafe Liquid metafield or setting output',
    severity: 'medium',
    points: -10,
    description: 'Detects metafield and merchant-setting output without context-appropriate escaping or serialization.',
    fix: 'Use escape for HTML text/attributes, json for JavaScript data, or metafield_tag for supported rich content.',
    requires: 'theme_app_extension',
  },
  {
    id: 'EXTERNAL_CDN_DEPENDENCY',
    status: 'investigate',
    title: 'External CDN dependency',
    severity: 'medium',
    points: 0,
    description: 'Investigates extension code loading dependencies or fetches from external non-Shopify domains.',
    fix: 'Bundle the dependency locally or self-host it behind a trusted boundary.',
    requires: 'theme_app_extension',
  },
  {
    id: 'INSECURE_WEBHOOK_URL',
    title: 'Webhook URL is not HTTPS',
    severity: 'high',
    points: -12,
    description: 'Detects webhook subscriptions configured with non-HTTPS absolute URLs.',
    fix: 'Change the webhook URI to use HTTPS.',
    guide: 'https://shopify.dev/docs/apps/webhooks',
    requires: 'webhooks',
  },
  {
    id: 'COMMITTED_SECRET',
    title: 'Committed secret or environment file',
    severity: 'high',
    points: -50,
    description: 'Detects environment files and common API key/token patterns in source files.',
    fix: 'Remove committed secrets, rotate exposed values, and store them in environment variables.',
  },

  {
    id: 'CREDENTIAL_LOG_LEAKAGE',
    title: 'Credential reaches a log sink',
    severity: 'high',
    points: -20,
    description: 'Detects direct credential flows to console and logger sinks.',
    fix: 'Remove credentials from logs; emit only safe redacted, hashed, or boolean-derived values.',
  },
  {
    id: 'CREDENTIAL_BROWSER_LEAKAGE',
    title: 'Credential reaches the client browser',
    severity: 'high',
    points: -20,
    description: 'Detects direct credential flows into responses, loaders, globals, DOM, and external requests.',
    fix: 'Keep credentials server-side and return only non-sensitive derived data.',
  },
  {
    id: 'KNOWN_CVE_IN_DEPENDENCY',
    title: 'Known CVE in dependency',
    severity: 'high',
    points: -20,
    description: 'Runs the selected JavaScript package manager audit against the committed lockfile.',
    fix: 'Upgrade the dependency to a patched version.',
  },

  {
    id: 'EXPIRING_OFFLINE_TOKEN',
    title: 'Expiring offline access tokens explicitly disabled',
    severity: 'medium',
    points: -10,
    description:
      'Verifies React Router expiring offline-token configuration and refresh-metadata storage compatibility.',
    fix: 'Enable expiringOfflineAccessTokens and ensure session storage persists expiry and refresh metadata.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/access-token-types/online-access-tokens',
  },
  {
    id: 'METAFIELD_OFFLINE_TOKEN',
    title: 'Metafield write using offline token context',
    severity: 'high',
    points: -15,
    description:
      'Detects metafield writes (metafieldsSet) in offline-token contexts. Online tokens provide user attribution and expiry.',
    fix: 'Use authenticate.admin(request) instead of unauthenticated.admin() for metafield writes.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/access-token-types/online-access-tokens',
  },
  {
    id: 'MISSING_EMBEDDED_CSP',
    title: 'Embedded app missing frame-ancestors CSP directive',
    severity: 'high',
    points: -10,
    description: 'Detects embedded apps that set document response headers but omit frame-ancestors.',
    fix: 'Add frame-ancestors to CSP, restricted to the authenticated shop domain and admin.shopify.com.',
    guide: 'https://shopify.dev/docs/apps/build/security/set-up-iframe-protection',
  },
  {
    id: 'MISSING_COMPLIANCE_WEBHOOKS',
    title: 'Missing mandatory GDPR compliance webhooks',
    severity: 'medium',
    points: -10,
    description:
      'Detects apps missing mandatory compliance webhooks (shop/redact, customers/data_request, customers/redact).',
    fix: 'Add the missing webhook subscriptions to shopify.app.toml.',
    guide: 'https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks',
  },
  {
    id: 'EOL_API_VERSION',
    title: 'End-of-life API version',
    severity: 'low',
    points: -5,
    description:
      'Detects parsed config and React Router server API versions past the 12-month support window and 30-day grace period.',
    fix: 'Update api_version in shopify.app.toml and the ApiVersion enum in shopify.server.ts.',
    guide: 'https://shopify.dev/docs/api/usage/versioning',
  },
  {
    id: 'WEAK_SHOP_VALIDATION',
    title: 'Shop domain validation regex is not anchored',
    severity: 'high',
    points: -15,
    description: 'Detects unanchored myshopify.com regexes that allow domain spoofing and token theft.',
    fix: 'Anchor the regex with ^ and $ to prevent prefix/suffix attacks.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/get-access-tokens/oauth',
  },
  {
    id: 'APP_PROXY_LIQUID_INJECTION',
    title: 'App proxy Liquid injection risk',
    severity: 'high',
    points: -20,
    description:
      'Detects app proxy endpoints that interpolate request parameters into active Liquid or HTML responses.',
    fix: "Don't interpolate user input into application/liquid responses. Use application/json or escape all input.",
    guide: 'https://shopify.dev/docs/apps/online-store/app-proxies',
  },
  {
    id: 'MISSING_TENANT_ISOLATION',
    title: 'Database query may not be scoped by shop',
    severity: 'high',
    points: -20,
    description: "Detects database queries in authenticated routes that don't reference the shop domain or session.",
    fix: "Add the authenticated shop to the query's where clause.",
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/session-tokens',
  },

  {
    id: 'OPEN_REDIRECT',
    title: 'Open redirect in auth callback',
    severity: 'medium',
    points: -12,
    description: 'Detects redirect targets taken from request parameters without validation.',
    fix: 'Validate the redirect URL against an allowlist of permitted domains.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization',
  },
  {
    id: 'UNAUTHENTICATED_ENDPOINT',
    title: 'Route handler lacks recognized auth verification',
    severity: 'high',
    points: -15,
    description:
      'Detects backend routes with no recognized auth guard or catch-block fallback to request-controlled shop input.',
    fix: 'Require Shopify session validation before accessing shop data.',
    guide: 'https://shopify.dev/docs/apps/auth',
    requires: 'has_backend',
  },
  {
    id: 'REQUEST_CONTROLLED_ADMIN_CONTEXT',
    title: 'Request input selects Admin API shop context',
    severity: 'high',
    points: -20,
    description:
      "Detects request-derived shop values passed into unauthenticated.admin(...), allowing callers to select another shop's Admin API context.",
    fix: 'Use the Admin API context returned by authenticate.admin(request). Never pass form, JSON, query, or route input into unauthenticated.admin(...).',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/online-access-tokens',
  },
  {
    id: 'RUNTIME_CONFIG_SCRIPT_EXECUTION',
    title: 'Runtime config field is executed as script',
    severity: 'high',
    points: -25,
    description: 'Detects config fields named as executable script used in files that inject or evaluate scripts.',
    fix: 'Ship storefront JavaScript as static versioned extension assets and treat runtime config as data only.',
    status: 'investigate',
  },

  {
    id: 'APP_PROXY_UNVERIFIED_SIGNATURE',
    title: 'App proxy request trusted without signature verification',
    severity: 'high',
    points: -15,
    description: 'Detects app proxy parameters read without visible signature verification.',
    fix: 'Verify app proxy signatures before trusting shop, customer, or path parameters.',
    guide: 'https://shopify.dev/docs/apps/build/online-store/app-proxies/authenticate-app-proxies',
    requires: 'app_proxy',
  },
  {
    id: 'REQUEST_DERIVED_SHOP_SCOPE',
    title: 'Query scoped by shop value taken from request input',
    severity: 'high',
    points: -15,
    description:
      'Detects queries whose shop scope comes from request params rather than the authenticated session. Presence of a shop key is not proof of scoping when its value is attacker-controlled.',
    fix: 'Scope the query with the shop from the authenticated session, or verify the supplied shop against a signed session or HMAC first.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/session-tokens',
  },
  {
    id: 'UNSCOPED_SHOP_CONFIG_WRITE',
    title: 'Config write trusts shop from request input',
    severity: 'high',
    points: -15,
    description:
      'Detects settings or metafield writes scoped by request-controlled shop input without visible auth verification.',
    fix: 'Derive the target shop from an authenticated session or verified HMAC.',
    guide: 'https://shopify.dev/docs/apps/build/authentication-authorization/session-tokens',
  },
  {
    id: 'STATIC_FRAME_ANCESTORS',
    title: 'Embedded app frame-ancestors uses a wildcard',
    severity: 'high',
    points: -12,
    description: 'Detects wildcard frame-ancestors CSP policies in Shopify app code.',
    fix: 'Build frame-ancestors per request from the authenticated shop domain and admin.shopify.com.',
    guide: 'https://shopify.dev/docs/apps/build/security/set-up-iframe-protection',
  },
  {
    id: 'OVERBROAD_DATA_ACCESS',
    title: 'Data access may exceed the current request',
    severity: 'medium',
    points: -10,
    description: 'Investigates reads that may expose data outside the authenticated shop or user boundary.',
    fix: 'Scope data access to the authenticated shop and minimum necessary records.',
  },
  {
    id: 'SSRF_REQUEST_FORGERY',
    title: 'Server-side request forgery risk',
    severity: 'high',
    points: -15,
    description: 'Investigates server-side requests whose destinations may be controlled by request input.',
    fix: 'Allowlist destinations and reject private, local, and unsafe network targets.',
  },
  {
    id: 'THEME_EXTENSION_XSS',
    title: 'Theme extension cross-site scripting risk',
    severity: 'high',
    points: -15,
    description: 'Investigates untrusted values rendered without safe escaping in theme extensions.',
    fix: 'Escape untrusted values and avoid raw HTML rendering.',
    requires: 'theme_app_extension',
  },
  {
    id: 'CSRF_MISSING_PROTECTION',
    title: 'Cross-site request forgery protection may be missing',
    severity: 'medium',
    points: -10,
    description: 'Investigates state-changing endpoints for missing request authenticity protections.',
    fix: 'Require an authenticated session and CSRF protection on state-changing requests.',
  },
  {
    id: 'MISSING_AUTHORIZATION_CHECK',
    title: 'Authorization check may be missing',
    severity: 'high',
    points: -15,
    description: 'Investigates authenticated handlers that may not authorize access to the requested resource.',
    fix: 'Authorize the actor and resource after authentication.',
  },
  {
    id: 'SCRIPT_TAG_URL_INJECTION',
    title: 'ScriptTag URL may be request controlled',
    severity: 'high',
    points: -15,
    description: 'Investigates ScriptTag writes whose source URL may be controlled by untrusted input.',
    fix: 'Remove ScriptTag usage or restrict sources to trusted versioned assets.',
  },
  {
    id: 'TEXT_SETTING_HTML_SMUGGLING',
    title: 'Text setting may be rendered as unsafe HTML',
    severity: 'high',
    points: -15,
    description: 'Investigates merchant-configurable text rendered as HTML without sanitization.',
    fix: 'Render settings as text or sanitize with a strict allowlist.',
  },
]
