/* eslint-disable @shopify/strict-component-boundaries */

/** Embed host workflow instructions only. Check prompts belong to the check-set package. */
import {readFileSync, writeFileSync} from 'node:fs'
import {dirname, join} from 'node:path'
import {fileURLToPath} from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const target = join(root, 'checks', 'embedded.ts')
const instructions = readFileSync(join(root, 'INSTRUCTIONS.md'), 'utf8')
const output = `// AUTO-GENERATED by app-security-engine/embed-checks.mjs — do not edit.
// Source of truth: ../INSTRUCTIONS.md. Check prompts are supplied by the installed check-set package.
/* eslint-disable no-template-curly-in-string */

// prettier-ignore
export const EMBEDDED_APP_SECURITY_INSTRUCTIONS = ${JSON.stringify(instructions)};
`
const args = process.argv.slice(2)
if (args.some((arg) => arg !== '--check')) {
  console.error('Usage: node embed-checks.mjs [--check]')
  process.exitCode = 1
} else if (args.includes('--check')) {
  if (readFileSync(target, 'utf8') !== output) {
    console.error('Embedded host instructions are stale; run pnpm --filter @shopify/app generate:app-security-checks.')
    process.exitCode = 1
  }
} else {
  writeFileSync(target, output)
}
