import {submissionTraceFixture, submissionTraceHashes} from './fixtures/submission-trace.js'
import {
  buildSubmission,
  SUBMISSION_SCHEMA_VERSION,
  validateTrace,
  type AppDoctorSubmission,
  type BuildSubmissionOptions,
} from '../index.js'
import {readFile} from '@shopify/cli-kit/node/fs'
import {joinPath, moduleDirectory} from '@shopify/cli-kit/node/path'
import {describe, expect, test} from 'vitest'

const fixturesDirectory = joinPath(moduleDirectory(import.meta.url), 'fixtures')

async function jsonFixture<T>(name: string): Promise<T> {
  return JSON.parse(await readFile(joinPath(fixturesDirectory, name))) as T
}

const options: BuildSubmissionOptions = {
  cliVersion: '3.99.0',
  submittedAt: '2026-09-01T09:30:00.000Z',
  versionTag: 'v1.2.3',
  feedback: 'The result for /Users/example/app included AKIA1234567890ABCDEF inaccurately.',
}

describe('buildSubmission', () => {
  test('validates the source fixture before mapping and matches the independently pinned golden payload', async () => {
    // This assertion must run before buildSubmission so a malformed fixture cannot
    // make mapper expectations look correct. The golden file is hand-pinned and
    // must never be generated by buildSubmission.
    expect(validateTrace(structuredClone(submissionTraceFixture))).toEqual({valid: true, errors: []})
    const expected = await jsonFixture<AppDoctorSubmission>('submission.json')

    expect(expected.schemaVersion).toBe(SUBMISSION_SCHEMA_VERSION)
    expect(expected.report.findings.map(({fingerprint}) => fingerprint)).toEqual([
      submissionTraceHashes.deterministicFingerprint,
      submissionTraceHashes.agentFingerprint,
      submissionTraceHashes.externalFingerprint,
    ])
    expect(expected.report.findings[1]!.prompt_hash).toBe(submissionTraceHashes.agentPromptHash)
    expect(expected.report.checks_executed[1]!.prompt_hash).toBe(submissionTraceHashes.agentPromptHash)
    expect(expected.report.checks_executed[4]!.prompt_hash).toBe(submissionTraceHashes.unresolvedPromptHash)
    expect(expected.report.attestation.trace_digest).toBe(submissionTraceHashes.traceDigest)
    expect(buildSubmission(structuredClone(submissionTraceFixture), options)).toEqual(expected)
  })

  test.each(['/Users/alice/private-app/server.ts', 'eval(req.body.code)'])(
    'replaces external title %j only in the submission',
    (title) => {
      const trace = structuredClone(submissionTraceFixture)
      const externalFinding = trace.findings.find((finding) => finding.source === 'external')!
      externalFinding.title = title
      const originalTrace = structuredClone(trace)

      const submission = buildSubmission(trace, options)

      expect(submission.report.findings.find((finding) => finding.source === 'external')).toMatchObject({
        title: 'External finding',
        fingerprint: externalFinding.fingerprint,
      })
      expect(JSON.stringify(submission)).not.toContain(title)
      expect(
        submission.report.findings.filter((finding) => finding.source !== 'external').map(({title}) => title),
      ).toEqual(trace.findings.filter((finding) => finding.source !== 'external').map(({title}) => title))
      expect(trace).toEqual(originalTrace)
    },
  )

  test('omits suppression justifications without changing the local trace or suppression linkage', () => {
    const trace = structuredClone(submissionTraceFixture)
    const suppression = trace.suppressions[0]!
    suppression.justification = 'Accepted eval(req.body.code) in /Users/alice/private-app/server.ts during migration'
    const originalTrace = structuredClone(trace)

    const submission = buildSubmission(trace, options)

    expect(submission.report.suppressions).toEqual([
      {
        id: suppression.id,
        finding_fingerprint: suppression.finding_fingerprint,
        provenance: {
          source: suppression.provenance.source,
          created_at: suppression.provenance.created_at,
        },
      },
    ])
    expect(
      submission.report.findings.find((finding) => finding.fingerprint === suppression.finding_fingerprint),
    ).toMatchObject({
      suppressed: true,
      suppression_id: suppression.id,
    })
    expect(JSON.stringify(submission)).not.toContain(suppression.justification)
    expect(trace).toEqual(originalTrace)
  })

  test('emits a null version tag when no app version is supplied', () => {
    const submission = buildSubmission(structuredClone(submissionTraceFixture), {
      cliVersion: '3.99.0',
      submittedAt: '2026-09-01T09:30:00.000Z',
    })

    expect(submission.report.metadata).toEqual({version_tag: null})
    expect(submission.report.feedback).toBeNull()
  })

  test('does not serialize the fixture’s excluded structural fields or unknown sentinels', async () => {
    const forbiddenValues = await jsonFixture<string[]>('submission-forbidden-values.json')
    const serialized = JSON.stringify(buildSubmission(structuredClone(submissionTraceFixture), options))

    for (const forbiddenValue of forbiddenValues) expect(serialized).not.toContain(forbiddenValue)
  })

  test('applies a second redaction pass to every free-text output field', () => {
    const secret = 'AKIA1234567890ABCDEF'
    const trace = structuredClone(submissionTraceFixture)
    const mutableEngine = trace.engine as unknown as Record<string, string>
    mutableEngine.name = `engine-${secret}`
    mutableEngine.version = `version-${secret}`
    mutableEngine.ruleset = `ruleset-${secret}`
    trace.findings[0]!.title = `CVE detected: ${secret}`

    const submission = buildSubmission(trace, {
      cliVersion: '3.99.0',
      submittedAt: '2026-09-01T09:30:00.000Z',
      versionTag: `version-${secret}`,
    })
    const serialized = JSON.stringify(submission)

    expect(serialized).not.toContain(secret)
    expect(submission.report.findings[0]!.title).toContain('[REDACTED:20]')
    expect(submission.report.metadata.version_tag).toContain('[REDACTED:20]')
  })

  test('preserves feedback exactly without applying the free-text redactor', () => {
    const feedback = 'The result for /Users/example/app included AKIA1234567890ABCDEF inaccurately.'

    const submission = buildSubmission(structuredClone(submissionTraceFixture), {...options, feedback})

    expect(submission.report.feedback).toBe(feedback)
  })

  test('keeps the public package and CVE identifiers in a known-CVE title', () => {
    const submission = buildSubmission(structuredClone(submissionTraceFixture), options)

    expect(submission.report.findings[0]!.title).toBe('Vulnerable package lodash (CVE-2026-0001)')
  })
})
