import {submissionTraceFixture, submissionTraceHashes} from './fixtures/submission-trace.js'
import {buildSubmission} from '../submission/index.js'
import {validateTrace} from '../trace/index.js'
import {readFile} from '@shopify/cli-kit/node/fs'
import {joinPath, moduleDirectory} from '@shopify/cli-kit/node/path'
import {describe, expect, test} from 'vitest'
import type {AppDoctorSubmission} from '../submission/index.js'

const fixturesDirectory = joinPath(moduleDirectory(import.meta.url), 'fixtures')

async function jsonFixture<T>(name: string): Promise<T> {
  return JSON.parse(await readFile(joinPath(fixturesDirectory, name))) as T
}

const options = {
  cliVersion: '3.99.0',
  submittedAt: '2026-09-01T09:30:00.000Z',
  versionTag: 'v1.2.3',
  sourceControlUrl: 'https://github.com/example/app/tree/v1.2.3',
}

describe('buildSubmission', () => {
  test('validates the source fixture before mapping and matches the independently pinned golden payload', async () => {
    // This assertion must run before buildSubmission so a malformed fixture cannot
    // make mapper expectations look correct. The golden file is hand-pinned and
    // must never be generated by buildSubmission.
    expect(validateTrace(structuredClone(submissionTraceFixture))).toEqual({valid: true, errors: []})
    const expected = await jsonFixture<AppDoctorSubmission>('submission.json')

    expect(expected.report.findings.map(({fingerprint}) => fingerprint)).toEqual([
      submissionTraceHashes.deterministicFingerprint,
      submissionTraceHashes.agentFingerprint,
      submissionTraceHashes.externalFingerprint,
    ])
    expect(expected.report.findings[1]!.prompt_hash).toBe(submissionTraceHashes.agentPromptHash)
    expect(expected.report.checks_executed[1]!.prompt_hash).toBe(submissionTraceHashes.agentPromptHash)
    expect(expected.report.checks_executed[4]!.prompt_hash).toBe(submissionTraceHashes.unresolvedPromptHash)
    expect(expected.report.attestation.trace_digest).toBe(submissionTraceHashes.traceDigest)
    expect(buildSubmission(structuredClone(submissionTraceFixture), options)).toEqual(expected)
  })

  test('does not serialize the fixture’s excluded structural fields or unknown sentinels', async () => {
    const forbiddenValues = await jsonFixture<string[]>('submission-forbidden-values.json')
    const serialized = JSON.stringify(buildSubmission(structuredClone(submissionTraceFixture), options))

    for (const forbiddenValue of forbiddenValues) expect(serialized).not.toContain(forbiddenValue)
  })

  test('applies a second redaction pass to every free-text output field', () => {
    const secret = 'AKIA1234567890ABCDEF'
    const trace = structuredClone(submissionTraceFixture)
    const mutableEngine = trace.engine as unknown as Record<string, string>
    mutableEngine.name = `engine-${secret}`
    mutableEngine.version = `version-${secret}`
    mutableEngine.ruleset = `ruleset-${secret}`
    trace.findings[0]!.title = `CVE detected: ${secret}`
    trace.suppressions[0]!.justification = `Approved with ${secret}`

    const submission = buildSubmission(trace, {
      cliVersion: '3.99.0',
      submittedAt: '2026-09-01T09:30:00.000Z',
      versionTag: `version-${secret}`,
      sourceControlUrl: `https://example.com/${secret}`,
    })
    const serialized = JSON.stringify(submission)

    expect(serialized).not.toContain(secret)
    expect(submission.report.findings[0]!.title).toContain('[REDACTED:20]')
    expect(submission.report.suppressions[0]!.justification).toContain('[REDACTED:20]')
    expect(submission.report.metadata.version_tag).toContain('[REDACTED:20]')
    expect(submission.report.metadata.source_control_url).toContain('[REDACTED:20]')
  })

  test('keeps the public package and CVE identifiers in a known-CVE title', () => {
    const submission = buildSubmission(structuredClone(submissionTraceFixture), options)

    expect(submission.report.findings[0]!.title).toBe('Vulnerable package lodash (CVE-2026-0001)')
  })
})
