// This is an autogenerated file. Don't edit this file manually.
export interface appconfiguse {
  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''

  /**
   * The path to your app directory.
   */
  '--path <value>'?: string

  /**
   * Reset current configuration.
   */
  '--reset'?: ''
}
