// This is an autogenerated file. Don't edit this file manually.
export interface themeinfo {
  /**
   * Disable color output.
   */
  '--no-color'?: ''

  /**
   * Increase the verbosity of the logs.
   */
  '--verbose'?: ''
}
