name: "Download and publish test coverage"
description: "Downloads test coverage stats from the base branch, publishes a comment with a summary"
inputs:
  base-branch-name:
    required: true
    description: "Name of the branch to compare coverage with"
runs:
  using: "composite"
  steps:
    # Strips forward slashes and dots as not supported by artifact commands
    - name: Clean base ref name
      shell: bash
      env:
        SAFE_BASE_REF_NAME: "${{ inputs.base-branch-name }}"
      run: |
        SAFE_BASE_REF_NAME=${{ env.SAFE_BASE_REF_NAME }}
        SAFE_BASE_REF_NAME=${SAFE_BASE_REF_NAME//[\/.]/}
        echo SAFE_BASE_REF_NAME=${SAFE_BASE_REF_NAME} >> $GITHUB_ENV
    - name: Download artifact
      continue-on-error: true
      id: download-artifact
      # We use this action and not Github's default, due to https://github.com/actions/download-artifact/issues/3
      uses: dawidd6/action-download-artifact@e6e25ac3a2b93187502a8be1ef9e9603afc34925 # pin@v2.24.2
      with:
        workflow: shopify-cli.yml
        workflow_conclusion: success
        branch: ${{ inputs.base-branch-name }}
        name: ${{ env.SAFE_BASE_REF_NAME }}--coverage-report
        if_no_artifact_found: ignore
    - uses: ArtiomTr/jest-coverage-report-action@9f733792c44d05327cb371766bf78a5261e43936 # pin@v2.1.2
      id: coverage
      with:
        annotations: none
        output: report-markdown
        coverage-file: "./report.json"
        base-coverage-file: "./baseline-report.json"
        threshold: 0
    - uses: marocchino/sticky-pull-request-comment@fcf6fe9e4a0409cd9316a5011435be0f3327f1e1 # pin@v2.3.1
      with:
        message: ${{ steps.coverage.outputs.report }}
