name: "Download and publish test coverage"
description: "Downloads test coverage stats from the base branch, publishes a comment with a summary"
runs:
  using: "composite"
  steps:
    # Strips forward slashes and dots as not supported by artifact commands
    - name: Clean base ref name
      shell: bash
      env:
          SAFE_BASE_REF_NAME: "${{ github.base_ref }}"
      run: |
        SAFE_BASE_REF_NAME=${{ env.SAFE_BASE_REF_NAME }}
        SAFE_BASE_REF_NAME=${SAFE_BASE_REF_NAME//[\/.]/}
        echo SAFE_BASE_REF_NAME=${SAFE_BASE_REF_NAME} >> $GITHUB_ENV
    - uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: ${{ env.SAFE_BASE_REF_NAME }}--coverage-report
    - uses: ArtiomTr/jest-coverage-report-action@v2.1.2
      id: coverage
      with:
        output: report-markdown
        coverage-file: "./report.json"
        base-coverage-file: "./baseline-report.json"
        threshold: 0
    - uses: marocchino/sticky-pull-request-comment@v2.3.1
      with:
        message: ${{ steps.coverage.outputs.report }}
