import Command from '@shopify/cli-kit/node/base-command'
import {Command as oclifCommand} from '@oclif/core'
import {mkdir, rmdir, writeFile} from '@shopify/cli-kit/node/fs'
import {cwd, joinPath} from '@shopify/cli-kit/node/path'

const shopifyDevDocsPath = joinPath(cwd(), '/docs-shopify.dev')
const commandInterfacePath = joinPath(shopifyDevDocsPath, '/commands')
const commandContentPath = joinPath(shopifyDevDocsPath, '/content/api/shopify-cli')
const commandExamplesPath = joinPath(shopifyDevDocsPath, '/examples/templated-apis/shopify-cli')
const generatedFileHeader = "This is an autogenerated file. Don't edit this file manually."

export type CommandWithMarkdown = oclifCommand.Loadable & {descriptionWithMarkdown?: string; summary?: string}

export interface CommandData {
  commandName: string
  fileName: string
  interfaceName: string
  category: string
  contentFolderName: string
}

interface CommandSection {
  category: string
  folderName: string
  title: string
}

const commandSections: CommandSection[] = [
  {category: 'app', folderName: 'app', title: 'Shopify CLI App commands'},
  {category: 'theme', folderName: 'theme', title: 'Shopify CLI Theme commands'},
  {category: 'hydrogen', folderName: 'hydrogen', title: 'Shopify CLI Hydrogen commands'},
  {category: 'store', folderName: 'store', title: 'Shopify CLI Store commands'},
  {category: 'general commands', folderName: 'general-commands', title: 'General commands'},
]

const topicSectionLookup = new Map(commandSections.map((section) => [section.folderName, section]))
const generalCommandsSection = commandSections[commandSections.length - 1]!

export default class DocsGenerate extends Command {
  static description = 'Generate CLI commands documentation'
  static hidden = true

  async run(): Promise<void> {
    const commands = this.config.commands as CommandWithMarkdown[]

    // Remove all files and recreate the folders to avoid leaving orphaned command docs behind.
    await Promise.all([rmdir(commandInterfacePath), rmdir(commandContentPath), rmdir(commandExamplesPath)])
    await Promise.all([mkdir(commandInterfacePath), mkdir(commandContentPath), mkdir(commandExamplesPath)])

    // Sort by length to ensure parent topics are processed first, so hidden topics hide their children.
    const sortedCommands = commands
      .sort((ca, cb) => ca.id.length - cb.id.length)
      .filter((command) => !isHidden(command))
    const commandData = sortedCommands.map((command) => {
      return {command, data: extractCommandData(command)}
    })

    const promises = commandData.flatMap(({command, data}) => {
      return [
        writeCommandFlagInterface(command, data),
        writeCommandReferencePage(command, data),
        writeCommandExample(command, data),
      ]
    })

    commandSections.forEach((section) => {
      promises.push(writeCommandSectionIndex(section))
    })

    promises.push(writeCommandSidebar(commandData.map(({data}) => data)))

    await Promise.all(promises)
  }
}

// By default we hide oclif commands that are not part of the Shopify CLI documentation
const hiddenTopics: string[] = ['commands', 'help', 'plugins']

function isHidden(command: oclifCommand.Loadable) {
  // Some commands rely on the hidden property of the parent topic, but is not returned in the oclif command object
  if (command.hidden) {
    hiddenTopics.push(command.id)
    return true
  }

  // User plugins are installed locally and are not part of the Shopify CLI documentation
  if (command.pluginType === 'user') return true
  return hiddenTopics.some((topic) => command.id.startsWith(`${topic}:`))
}

export function extractCommandData(command: CommandWithMarkdown) {
  const commandName = command.id.replace(/[:]/g, ' ')
  const fileName = command.id.replace(/[:]/g, '-')
  const interfaceName = command.id.replace(/[:-]/g, '')
  const section = getCommandSection(command.id)
  return {
    commandName,
    fileName,
    interfaceName,
    category: section.category,
    contentFolderName: section.folderName,
  }
}

function getCommandSection(commandId: string) {
  const [topic] = commandId.split(':')
  return topicSectionLookup.get(topic ?? '') ?? generalCommandsSection
}

function visibleFlags(command: oclifCommand.Loadable) {
  return Object.values(command.flags).filter((flag) => flag && !flag.hidden)
}

function commandDescription(command: CommandWithMarkdown) {
  return formatCommandContent(command.descriptionWithMarkdown ?? command.description ?? command.summary ?? '')
}

function commandFrontmatterDescription(command: CommandWithMarkdown) {
  const source = commandDescription(command)
  const [firstParagraph = ''] = source.trim().split(/\n\s*\n/)
  return firstParagraph
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/`/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function formatCommandContent(content: string) {
  return content.replace(/<%=\s*config\.bin\s*%>/g, 'shopify')
}

function commandTitle(value: string) {
  return value ? `${value[0]?.toUpperCase()}${value.slice(1)}` : value
}

function yamlString(value: string) {
  return JSON.stringify(value)
}

function frontmatterString(value: string) {
  return JSON.stringify(value.replace(/\n+/g, ' ').trim())
}

// Generates an interface for the flags of a command and writes it to a file
export async function writeCommandFlagInterface(
  command: oclifCommand.Loadable,
  {commandName, fileName, interfaceName}: CommandData,
) {
  const flagsDetails = visibleFlags(command)
    .map((flag) => {
      const flagName = flag.name
      if (!flagName) return
      const flagDescription = flag.description ?? ''
      const char = flag.char ? `-${flag.char}, ` : ''
      const type = flag.type === 'option' ? 'string' : "''"
      const value = flag.type === 'option' ? ' <value>' : ''
      const optional = flag.required ? '' : '?'
      // eslint-disable-next-line no-negated-condition
      const envValue = flag.env !== undefined ? ` @environment ${flag.env}` : ''
      const flagContent = `  /**
   * ${flagDescription}
   *${envValue}
   */
  '${char}--${flagName}${value}'${optional}: ${type}`
      // Example output: '-c, --config <value>'?: string
      return flagContent
    })
    .filter((str) => str && str?.length > 0)
    .join('\n\n')

  const commandContent = `// ${generatedFileHeader}
/**
 * The following flags are available for the \`${commandName}\` command:
 * @publicDocs
 */
export interface ${interfaceName} {
${flagsDetails}
}
`
  await mkdir(`${commandInterfacePath}/interfaces`)
  await writeFile(`${commandInterfacePath}/interfaces/${fileName}.interface.ts`, commandContent)
}

export async function writeCommandReferencePage(command: CommandWithMarkdown, commandData: CommandData) {
  const {category, commandName, contentFolderName, fileName, interfaceName} = commandData
  const description = commandDescription(command)
  const flags = visibleFlags(command)
  const flagsSection = flags.length > 0 ? `\n<TypeDefinition typeName="${interfaceName}" displayName="Flags" />\n` : ''
  const commandContent = `---
title: ${commandName}
description: ${frontmatterString(commandFrontmatterDescription(command))}
category: ${category}
generated_from: shopify/cli
---

{/* ${generatedFileHeader} */}

${description}
${flagsSection}
<ExampleSwitcher displayRightColumn>

  <Example title="${commandTitle(commandName)}">
    <CodeBlock title="${commandName}" src="templated-apis/shopify-cli/${fileName}/${fileName}.sh" />
  </Example>

</ExampleSwitcher>
`

  await mkdir(`${commandContentPath}/${contentFolderName}`)
  await writeFile(`${commandContentPath}/${contentFolderName}/${fileName}.mdx`, commandContent)
}

export async function writeCommandExample(command: oclifCommand.Loadable, {commandName, fileName}: CommandData) {
  const flags = visibleFlags(command)
  const flagsSuffix = flags.length > 0 ? ' [flags]' : ''
  await mkdir(`${commandExamplesPath}/${fileName}`)
  await writeFile(`${commandExamplesPath}/${fileName}/${fileName}.sh`, `shopify ${commandName}${flagsSuffix}\n`)
}

export async function writeCommandSectionIndex(section: CommandSection) {
  const commandContent = `---
title: ${section.title}
show_sidebar_anchor_links: false
generated_from: shopify/cli
---

{/* ${generatedFileHeader} */}

<Category category="${section.category}" />
`

  await mkdir(`${commandContentPath}/${section.folderName}`)
  await writeFile(`${commandContentPath}/${section.folderName}/index.mdx`, commandContent)
}

export async function writeCommandSidebar(commands: CommandData[]) {
  const commandsBySection = new Map<string, CommandData[]>()
  commandSections.forEach((section) => commandsBySection.set(section.folderName, []))
  commands.forEach((command) => commandsBySection.get(command.contentFolderName)?.push(command))

  const sidebarSections = commandSections
    .map((section) => {
      const sectionCommands = commandsBySection.get(section.folderName) ?? []
      const commandLinks = sectionCommands
        .sort((ca, cb) => ca.commandName.localeCompare(cb.commandName))
        .map((command) => {
          return `              ${command.fileName}:
                label: ${yamlString(command.commandName)}
                url: ${yamlString(`/docs/api/shopify-cli/${section.folderName}/${command.fileName}`)}`
        })
        .join('\n')

      return `          ${section.folderName}:
            label: ${yamlString(section.category)}
            children:
              overview:
                label: Overview
                url: ${yamlString(`/docs/api/shopify-cli/${section.folderName}`)}
${commandLinks}`
    })
    .join('\n')

  const sidebarContent = `# ${generatedFileHeader}
en:
  sidebar:
    api:
      shopify_cli:
        links:
${sidebarSections}
`

  await writeFile(`${commandContentPath}/sidebar.yml`, sidebarContent)
}
