import {CommandData, CommandWithMarkdown, extractCommandData, writeCommandFlagInterface} from './generate.js'
import {inTemporaryDirectory, readFile} from '@shopify/cli-kit/node/fs'
import {cwd, joinPath} from '@shopify/cli-kit/node/path'
import {describe, test, vi, expect} from 'vitest'

vi.mock('@shopify/cli-kit/node/path', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@shopify/cli-kit/node/path')>()
  return {
    ...actual,
    cwd: vi.fn(),
  }
})

const testCommand: CommandWithMarkdown = {
  aliases: [],
  args: {},
  flags: {
    flag1: {
      name: 'flag1',
      type: 'option',
      char: 'f',
      description: 'flag description',
    },
    flag2: {
      name: 'flag2',
      type: 'boolean',
      char: 'a',
      description: 'another flag description',
      env: 'FLAG_ENV',
      allowNo: false,
    },
  },
  descriptionWithMarkdown: 'command markdown description',
  description: 'command description',
  summary: 'command summary',
  hidden: false,
  hiddenAliases: [],
  id: 'topic:test-command',
  load: () => Promise.resolve({} as any),
}

const commandData: CommandData = {
  commandName: 'topic test-command',
  fileName: 'topic-test-command',
  interfaceName: 'topictestcommand',
}

describe('extractCommandData', () => {
  test('returns the correct data', () => {
    expect(extractCommandData(testCommand)).toEqual(commandData)
  })
})

describe('writeCommandFlagInterface', () => {
  test('writes the correct content to the file', async () => {
    await inTemporaryDirectory(async (tmpDir) => {
      // Given
      vi.mocked(cwd).mockReturnValue(tmpDir)
      const filePath = joinPath(tmpDir, 'docs-shopify.dev/commands/interfaces/topic-test-command.interface.ts')

      // When
      await writeCommandFlagInterface(testCommand, commandData)

      // Then
      const content = await readFile(filePath)
      expect(content).toBe(`// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the \`topic test-command\` command:
 * @publicDocs
 */
export interface topictestcommand {
  /**
   * flag description
   *
   */
  '-f, --flag1 <value>'?: string

  /**
   * another flag description
   * @environment FLAG_ENV
   */
  '-a, --flag2'?: ''
}
`)
    })
  })

  test('writes the correct content for a command with no flags', async () => {
    await inTemporaryDirectory(async (tmpDir) => {
      // Given
      vi.mocked(cwd).mockReturnValue(tmpDir)
      const filePath = joinPath(tmpDir, 'docs-shopify.dev/commands/interfaces/topic-test-command.interface.ts')

      // When
      await writeCommandFlagInterface({...testCommand, flags: {}}, commandData)

      // Then
      const content = await readFile(filePath)
      expect(content).toBe(`// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the \`topic test-command\` command:
 * @publicDocs
 */
export interface topictestcommand {

}
`)
    })
  })
})
