import {
  CommandData,
  CommandWithMarkdown,
  extractCommandData,
  writeCommandExample,
  writeCommandFlagInterface,
  writeCommandReferencePage,
  writeCommandSectionIndex,
  writeCommandSidebar,
} from './generate.js'
import {writeFile} from '@shopify/cli-kit/node/fs'
import {describe, test, vi, expect} from 'vitest'

vi.mock('@shopify/cli-kit/node/fs')

const testCommand: CommandWithMarkdown = {
  aliases: [],
  args: {},
  flags: {
    flag1: {
      name: 'flag1',
      type: 'option',
      char: 'f',
      description: 'flag description',
    },
    flag2: {
      name: 'flag2',
      type: 'boolean',
      char: 'a',
      description: 'another flag description',
      env: 'FLAG_ENV',
      allowNo: false,
    },
  },
  descriptionWithMarkdown: 'command markdown description',
  description: 'command description',
  summary: 'command summary',
  hidden: false,
  hiddenAliases: [],
  id: 'topic:test-command',
  load: () => Promise.resolve({} as any),
}

const commandData: CommandData = {
  commandName: 'topic test-command',
  fileName: 'topic-test-command',
  interfaceName: 'topictestcommand',
  category: 'general commands',
  contentFolderName: 'general-commands',
}

describe('extractCommandData', () => {
  test('returns the correct data for a general command', () => {
    expect(extractCommandData(testCommand)).toEqual(commandData)
  })

  test('returns the correct data for a topic command', () => {
    expect(extractCommandData({...testCommand, id: 'app:dev'})).toEqual({
      commandName: 'app dev',
      fileName: 'app-dev',
      interfaceName: 'appdev',
      category: 'app',
      contentFolderName: 'app',
    })
  })
})

describe('writeCommandFlagInterface', () => {
  test('calls writeFile with the correct content', async () => {
    await writeCommandFlagInterface(testCommand, commandData)

    expect(writeFile).toHaveBeenCalledWith(
      expect.stringContaining('docs-shopify.dev/commands/interfaces/topic-test-command.interface.ts'),
      `// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the \`topic test-command\` command:
 * @publicDocs
 */
export interface topictestcommand {
  /**
   * flag description
   *
   */
  '-f, --flag1 <value>'?: string

  /**
   * another flag description
   * @environment FLAG_ENV
   */
  '-a, --flag2'?: ''
}
`,
    )
  })

  test('calls writeFile with the correct content for a command with no flags', async () => {
    await writeCommandFlagInterface({...testCommand, flags: {}}, commandData)

    expect(writeFile).toHaveBeenCalledWith(
      expect.stringContaining('docs-shopify.dev/commands/interfaces/topic-test-command.interface.ts'),
      `// This is an autogenerated file. Don't edit this file manually.
/**
 * The following flags are available for the \`topic test-command\` command:
 * @publicDocs
 */
export interface topictestcommand {

}
`,
    )
  })
})

describe('writeCommandReferencePage', () => {
  test('writes a generated MDX command page with flags and examples', async () => {
    await writeCommandReferencePage(testCommand, commandData)

    expect(writeFile).toHaveBeenCalledWith(
      expect.stringContaining('docs-shopify.dev/content/api/shopify-cli/general-commands/topic-test-command.mdx'),
      `---
title: topic test-command
description: "command markdown description"
category: general commands
generated_from: shopify/cli
---

{/* This is an autogenerated file. Don't edit this file manually. */}

command markdown description

<TypeDefinition typeName="topictestcommand" displayName="Flags" />

<ExampleSwitcher displayRightColumn>

  <Example title="Topic test-command">
    <CodeBlock title="topic test-command" src="templated-apis/shopify-cli/topic-test-command/topic-test-command.sh" />
  </Example>

</ExampleSwitcher>
`,
    )
  })

  test('omits the flags component when a command has no visible flags', async () => {
    await writeCommandReferencePage({...testCommand, flags: {}}, commandData)

    expect(writeFile).toHaveBeenCalledWith(
      expect.any(String),
      expect.not.stringContaining('<TypeDefinition typeName="topictestcommand" displayName="Flags" />'),
    )
  })

  test('replaces oclif bin placeholders in generated command descriptions', async () => {
    await writeCommandReferencePage(
      {
        ...testCommand,
        descriptionWithMarkdown: 'List all <%= config.bin %> commands.',
        description: 'List all <%= config.bin %> commands.',
      },
      commandData,
    )

    expect(writeFile).toHaveBeenCalledWith(
      expect.any(String),
      expect.stringContaining(`description: "List all shopify commands."`),
    )
    expect(writeFile).toHaveBeenCalledWith(expect.any(String), expect.stringContaining('List all shopify commands.'))
    expect(writeFile).toHaveBeenCalledWith(expect.any(String), expect.not.stringContaining('<%= config.bin %>'))
  })
})

describe('writeCommandExample', () => {
  test('writes a generated shell example for a command with flags', async () => {
    await writeCommandExample(testCommand, commandData)

    expect(writeFile).toHaveBeenCalledWith(
      expect.stringContaining(
        'docs-shopify.dev/examples/templated-apis/shopify-cli/topic-test-command/topic-test-command.sh',
      ),
      'shopify topic test-command [flags]\n',
    )
  })

  test('omits the flags suffix when a command has no visible flags', async () => {
    await writeCommandExample({...testCommand, flags: {}}, commandData)

    expect(writeFile).toHaveBeenCalledWith(expect.any(String), 'shopify topic test-command\n')
  })
})

describe('writeCommandSectionIndex', () => {
  test('writes a generated category index page', async () => {
    await writeCommandSectionIndex({
      category: 'app',
      folderName: 'app',
      title: 'Shopify CLI App commands',
    })

    expect(writeFile).toHaveBeenCalledWith(
      expect.stringContaining('docs-shopify.dev/content/api/shopify-cli/app/index.mdx'),
      `---
title: Shopify CLI App commands
show_sidebar_anchor_links: false
generated_from: shopify/cli
---

{/* This is an autogenerated file. Don't edit this file manually. */}

<Category category="app" />
`,
    )
  })
})

describe('writeCommandSidebar', () => {
  test('writes a generated sidebar grouped by command section', async () => {
    await writeCommandSidebar([
      {...commandData, commandName: 'app dev', fileName: 'app-dev', category: 'app', contentFolderName: 'app'},
      commandData,
    ])

    expect(writeFile).toHaveBeenCalledWith(
      expect.stringContaining('docs-shopify.dev/content/api/shopify-cli/sidebar.yml'),
      expect.stringContaining(`          app:
            label: "app"
            children:
              overview:
                label: Overview
                url: "/docs/api/shopify-cli/app"
              app-dev:
                label: "app dev"
                url: "/docs/api/shopify-cli/app/app-dev"`),
    )
    expect(writeFile).toHaveBeenCalledWith(
      expect.stringContaining('docs-shopify.dev/content/api/shopify-cli/sidebar.yml'),
      expect.stringContaining(`          general-commands:
            label: "general commands"
            children:
              overview:
                label: Overview
                url: "/docs/api/shopify-cli/general-commands"
              topic-test-command:
                label: "topic test-command"
                url: "/docs/api/shopify-cli/general-commands/topic-test-command"`),
    )
  })
})
