name: Deprecate shopify-cli-extensions

on:
  workflow_dispatch:

jobs:
  release:
    name: Deprecate shopify-cli-extensions
    runs-on: ubuntu-latest
    steps:
      - name: Deprecate
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm deprecate @shopify/shopify-cli-extensions@"*" "Please use @shopify/cli instead."
          npm deprecate @shopify/ngrok@"*" "This package is deprecated."
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
