name: Release - Manual & Cron

on:
  schedule:
    - cron: '0 6 * * *' # 6:00 AM UTC every day
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        default: 'nightly'
        type: choice
        options:
          - nightly
          - latest
          - experimental

concurrency:
  group: changeset-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PNPM_VERSION: '10.11.1'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        with:
          fetch-depth: 1
      - name: Setup deps
        uses: ./.github/actions/setup-cli-deps
        with:
          node-version: 24.1.0
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        run:  pnpm release ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          SHOPIFY_CLI_BUILD_REPO: ${{ github.repository }}
