name: 'Shopify Security Code Scanner'

on: [push]

jobs:
  Security-Code-Scanner:
    uses: shopify/security-code-scanner/.github/workflows/main.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
