name: Shopify

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: shopify-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: theme-cli tests Ruby ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        version:
          - 3.1.0
          - 3.0.2
          - 2.7.5
        os:
          - macos-11
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true

      - name: Install Dependencies
        run: |
          cd packages/theme-cli
          ls -la
          cd ../theme
          ls -la
          bundle install

      - name: Run Tests
        run: |
          cd packages/theme-cli
          bundle exec rake test
  rubocop:
    name: Rubocop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - 3.1.0
        os:
          - macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true

      - name: Install Dependencies
        run: |
          cd packages/theme-cli
          bundle install

      - name: Rubocop
        run: |
          cd packages/theme-cli
          bundle exec rake rubocop
